### ISSUE TITLE
Eliminate MutationObserver usage with version integrated into Todoist?

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#10]
If integrated with Todoist, there's also some potential to increase performance by eliminating the use of `MutationObserver`.  This is used to detect when elements have changed, do various things in response.  For my usage of Todoist, this seems low priority.  It could be a problem for someone that has huge lists, though.  Currently when anything in the task display changes, the entire visible task list gets traversed.  Here's what these mutation observers are used for:

* If anything changes in the task list, it does various things ensuring that the cursor is in the right spot.  This one triggers a lot and usually does a full scan of the tasks. Ideally it would be removed.

* It notices when navigation has occurred, and if it has, puts the cursor on the first task.  This one is cheap, it is probably ok to leave it.

* Sometimes when items get selected rapidly, the top bar disappears.  todoist-shortcuts has a hack where it will quickly toggle the selection status of an item when it detects that this has happened.  There is also some CSS removing animation from the top bar, to make this hack invisible.  This one is cheap, doesn't need to be eliminated.

**Comment by amix** [comment]
@mgsloan Did you try to use signals? For example, try to connect to `Signals.connect("instant_refresh_interface", refreshListener)`. `refreshListener` should be triggered every time the interface is opened.

**Comment by mgsloan** [comment]
@amix Interesting!  todoist-shortcuts does not directly called any javascript functions that are part of Todoist, this is good stuff to know.  I'll hopefully look into it further when I get the time.

**Comment by mgsloan** [comment]
Going to go ahead and close this until there's a more concrete performance issue.  I don't see a good way of supporting the drag handle cursor without using a mutation observer.  It may be possible to use a more limited mutation observer, but on my machine and todo lists it seems to work fine.
