### ISSUE TITLE
Feature request: Shortcut for create new project + for 'add task and create project for it at the same time'

### ISSUE THREAD

**Issue by savolai** [mgsloan/todoist-shortcuts#100]

**Comment by savolai** [comment]
I'm just learning to use these shortcuts and loving that this project exists, thanks! I'm used to checkvist's keyboard shortcuts so these seem a bit arbitrary.

**Comment by mgsloan** [comment]
Hey, I'm so glad you appreciate it!

I don't currently have plans to add any bindings for managing projects.  My personal usage of Todoist barely ever involves manipulating projects, usually just manipulating tasks.  I can tolerate a bit of mouse usage when I'm doing such meta organization :)

The shortcuts were chosen to match GMail keyboard shortcuts which appear to be influenced by Vim.  So the upside is that a lot of the muscle memory will translate between GMail, Vim, Emacs evil mode, Google Calendar, etc.

**Comment by mgsloan** [comment]
Closing as wontfix, I don't plan to have project management bindings
