### ISSUE TITLE
Thank you . . . and . . .

### ISSUE THREAD

**Issue by RobSJacobs2411** [mgsloan/todoist-shortcuts#101]
Terrific extension for Todoist. Thanks!

My only question is are you going to update to include shortcuts for sections and some of the other new features added at the end of last year?

**Comment by mgsloan** [comment]
Hey, I'm glad you appreciate it!  I hope to get around to it at some point, but it's probably quite a bit of work.  It's currently tracked by https://github.com/mgsloan/todoist-shortcuts/issues/93

Good to know that there's some user interest in this feature.  I don't have specific plans for implementing it, but hopefully sometime!
