### ISSUE TITLE
Keyboard Shortcut for adding a sub-task doesn't work in task view

### ISSUE THREAD

**Issue by idonimni** [mgsloan/todoist-shortcuts#104]
It only works if I first press one of the other task manipulation keyboard shortcuts (like 'v') > 'Esc' >'q'.

**Comment by mgsloan** [comment]
Hmm, it works for me on standard todoist, but not on todoist beta.  Are you using todoist beta?

**Comment by idonimni** [comment]
no, I'm using standard Todoist.

Can you please describe the exact step by step keyboard presses that you do?

**Comment by mgsloan** [comment]
I press `i` to bring up the task view and then `q` to add a subtask.  `o` or `O` also works

**Comment by idonimni** [comment]
that's exactly what I did and it didn't work (with q). But with o it works!
please update the documentation :)

**Comment by mgsloan** [comment]
I suspect it is a difference of how keyhandling is behaving in your
environment, so I am not going to update the documentation.
