### ISSUE TITLE
[beta] 'Enter' key no longer edits task

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#105]
The [beta version](https://get.todoist.help/hc/en-us/articles/360008804540) released today (03/11/2020) is quite nice, but as usual it breaks a couple of useful shortcuts:

- the **Enter** key no longer edits the task at cursor but opens the task view. To edit a task, you have to use the mouse...
- the **i** key, which used to open the task view, does nothing.

On the bright side, nothing else is broken, far as I can tell. :-)

**Comment by mgsloan** [comment]
Thanks for reporting!  Fixed in version 71
