### ISSUE TITLE
Feature request: key binding to open link at task

### ISSUE THREAD

**Issue by fabiocpn** [mgsloan/todoist-shortcuts#107]
I honestly don't know if this is at all possible or not. But, in my workflow, many tasks have links that point to other websites (i.e. links to scientific articles that I have to read/reference). If at all possible, it would be great to have a keybind to open the first link on a task (Ctrl+Enter;Shift+Enter). 

Great work! This is a game-changer!

**Comment by GraphicThinkPad** [comment]
Hey there! I'm actually not the maintainer for this project, but shift + enter typically does exactly what you're describing. I'd noticed that the shortcut has been broken for me for a few days, but I wasn't sure if it was just an issue on my machine, so I didn't submit a ticket for it. So if shift + enter on a task doesn't click the first link of that task for you, the shortcut is broken and we should let Michael know!

**Comment by GraphicThinkPad** [comment]
Actually, I just did a bit of digging and noticed that the follow() function works properly, it's just that a link is never found for the function to click. Instead, "Didn't find a link to click" just gets logged to the console. @mgsloan just wanted to call that out so this is easier to fix.

**Comment by mgsloan** [comment]
Thanks for noticing that this is broken!  I believe that Todoist changed how it does links.

Fixed in version 71
