### ISSUE TITLE
[beta] New upstream 'm' shortcut interferes with section navigation mode

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#108]
(This is w.r.t the [beta version](https://get.todoist.help/hc/en-us/articles/360008804540) released on 03/11/2020.)

Upstream, the **m** key is now a shortcut for toggling visibility of the navigation menu, which is really nice, but it should be overridden when you're in section navigation mode.
Consider this:

1. You have a project named "Mammoth", say.
2. You click **g** to enter section navigation mode. It assigns **m** as the shortcut for Mammoth.
3. You click **m**, which correctly navigates you to Mammoth, _but_ the navigation menu is now hidden (or shown if you had it hidden before). You have to click **m** again to restore the previous visibility state.

In section navigation mode, alphanumeric keys should just be navigational shortcuts and shouldn't have any other functions.

**Comment by mgsloan** [comment]
Ah curious, thanks a bunch for reporting!  In version 71, the side pane will now always show when in navigation mode.  I haven't worked out how Todoist is receiving the `m` keystroke yet, so it's still doing two things.  But at least now the pane doesn't disappear!

Leaving this issue open to track a more complete fix.

**Comment by mgsloan** [comment]
I forget when this was fixed, but it was!
