### ISSUE TITLE
<bug> `g` shortcut causes project list to left align on Brave browser only

### ISSUE THREAD

**Issue by GraphicThinkPad** [mgsloan/todoist-shortcuts#109]
Starting today, whenever I hit the "g" shortcut to navigate through projects, the project list aligns itself all the way to the left. I checked Chrome, and the issue does not occur there--at least, not for me.

This is especially interesting since I don't have the Brave Shield running on Todoist, which is what usually causes websites to act up like this.

Gif attached for illustrative purposes.

![todoist_error](https://user-images.githubusercontent.com/26067990/76780835-0f676600-6784-11ea-864b-ad900f41c896.gif)

**Comment by ErikOsterud** [comment]
Just to add my own experience -
In Brave and Chrome:
I see this on the current todoist.com version, but not on the beta.todoist.com version where Todoist recently moved the projects list to the far left of the page.

**Comment by mgsloan** [comment]
Oops, yeah a fix in the last version for beta.todoist.com behavior went a
bit awry.  Should be fixed in version 72, which I've just uploaded.
