### ISSUE TITLE
todoist-shortcuts needs to use inefficient hacks for selection modification

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#11]
Quoting [the code](https://github.com/mgsloan/todoist-shortcuts/blob/fe3d249/src/todoist-shortcuts.js#L526):

```javascript
  // Given a task element, shift-clicks it. Unfortunately, todoist currently has
  // quite strange behavior:
  //
  // * Shift clicking a selected task deselects a single task.
  //
  // * Shift clicking an unselected task toggles the selection state of all the
  //   tasks between the current task and the other tasks.
```

This behavior is rather strange from a user perspective too, so there's also the benefit to normal usage there.

So, to select a single task, the following is done:

* Every single selected task is shift clicked to deselect
* The very first task and very last task is shift-clicked.  Now, every task is selected
* Every task that shouldn't be selected is shift-clicked to deselect it.

This was the only reliable and straightforward algorithm I could find for extending the current selection with a single additional item.

**Comment by amix** [comment]
Adding a task to look into this 👍

**Comment by amix** [comment]
@mgsloan You could call `ItemSelecter.deselectAll()` before doing a selection.

As an alternative you could also call `$removeClass($all("li", "selected"), "selected")`

**Comment by mgsloan** [comment]
Looks like there isn't direct access to `ItemSelecter.deselectAll()`.  However, it's very helpful to know that the classes in the DOM determine what is selected.  I wouldn't have guessed that would be the case, thanks!

**Comment by amix** [comment]
In the upcoming beta we'll make `ItemSelecter` a global object

**Comment by mgsloan** [comment]
Great, thanks! I've updated the code to use the `ItemSelecter`.  Simplifies things a bunch!
