### ISSUE TITLE
Not working in "upcoming" view

### ISSUE THREAD

**Issue by champagnealexandre** [mgsloan/todoist-shortcuts#110]
I know it's the beta, but those changes will eventually migrate to the prod version of Todoist so ;-)

Trying to go back one level (keystroke "h") seems to hang the extension. I'm really not familiar enough with Chrome extension to give more explanation than this. But I guess they changes the inner workings of the app somehow.

By the way : thank you so much for creating this! You totally made my day when I discovered it :-)

**Comment by mgsloan** [comment]
Hey, I've just released version 73 which fixes an initialization bug that could cause all kinds of problems.  With that version I do not see it hanging for "h" on beta.todoist.com.  Can you please check again with latest beta version / extension version? Thanks!

You're welcome, I'm so glad you appreciate my work on this!

**Comment by champagnealexandre** [comment]
Nope I've triple checked everything I could, removed/added back the extension, etc.

It works on todoist.com but not on _beta_.todoist.com.

**Comment by stianmandarin** [comment]
@mgsloan It doesn't work for me with the latest beta either.

**Comment by stianmandarin** [comment]
@mgsloan Any word on getting this working on the "Upcoming" view?

**Comment by mgsloan** [comment]
Wow, the choice of dom node attributes in that view is wildly different than the old "Next 7 days" view.  I took an initial attempt at it, but it's looking like the changes will be quite substantial.  I'd prefer to wait until it's on `todoist.com` or until the DOM choices are more uniform.  I know that sucks, but right now supporting both of them at once would be quite a lot of effort.

**Comment by stianmandarin** [comment]
@mgsloan Totally get it mate, thanks a bunch for the update

**Comment by champagnealexandre** [comment]
I understand as well! Let's hope Todoist speeds thing up as their beta is far superior right row IMO ;-)

And yeah thanks again for this extension ; really a life saver! Don't understand why it's not implemented directly into Todoist tbh.

**Comment by aays** [comment]
Apologies for bringing this issue back up, but 'Upcoming' view was just rolled out to `todoist.com` and I updated without realizing it would break the plugin's functionality :( Any updates?

Thanks a ton again for this extension - not sure what I would do without it!

**Comment by mgsloan** [comment]
Hi, yeah, I'll probably look into it soon.  It seems like this "Upcoming" has an entirely new way of displaying tasks, so that causes a ton of work to update it...  While also supporting the old way.

Workaround for now is to not use the upcoming view.

**Comment by champagnealexandre** [comment]
Do you know if Todoist have plan to integrate your extension officially? This seems like a cats & mouse game to chase the latest changes and make it work every time with your plugin.

**Comment by mgsloan** [comment]
I've made some progress on this.  It seems like this is almost a complete rewrite of Todoist's task UI.  It may look the same, but everything is different, even the menu.

I ran into a bit of a blocker, which is that the "More actions" menu items do not have CSS classes to distinguish the different items.  This isn't entirely a blocker, the same thing is true of the buttons in the task view.  There I used the `aria-label` attribute, but that will only work on english.  I'd prefer to avoid doing that hack.  I've emailed folks at Doist about this.

**Comment by stianmandarin** [comment]
@mgsloan Just wanna say thanks again for sticking with this project despite the changes from Doist. I'm not even using the Upcoming view at all. Set my start-up to a filter where your plugin works. Life without it makes Todoist unbearably slow, heh

**Comment by mgsloan** [comment]
I've released a hacky workaround in version 85!  It only works on the english version of Todoist, and operations on the cursored task will cause the task to be selected.  A proper fix is tracked by #137, which should be feasible once Doist devs add the disambiguating classes.

**Comment by mgsloan** [comment]
@stianmandarin Thanks for the kind words!  I'm glad you appreciate the extension

**Comment by mgsloan** [comment]
Update: The helpful folks at Doist added the disambiguating attributes to the DOM!  So now with todoist-shortcuts version 90, in the beta version of Todoist, the extension works for non-english locales :D
