### ISSUE TITLE
[beta] Sorting is smart-broken

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#112]
(I think this started in the 3/19 [beta](https://get.todoist.help/hc/en-us/articles/360008804540).)

The only sorting shortcut that works now is **s**, and it has been "smartified" to sort by priority or by date as it sees fit. The **p** and **n** keys are duds.
Personally, I could live without **p** -- the new, juiced up **s** mostly does the right thing -- but **n** is a sad loss. :pray:

**Comment by mgsloan** [comment]
Thanks for reporting!  Turns out my fixes to keyboard handling were incomplete.  Let's hope this latest iteration solves it for good.  Seems to be fixed in version 75 which I've just released.

**Comment by ismig** [comment]
Works great; thanks! :100:

**Comment by mgsloan** [comment]
Thanks for confirming :+1:
