### ISSUE TITLE
Feature request: select postpone date when rescheduling recurring tasks

### ISSUE THREAD

**Issue by CJSF2323** [mgsloan/todoist-shortcuts#113]
Currently, can only select from the following options

![image](https://user-images.githubusercontent.com/22968514/77914024-426d2780-7263-11ea-9065-85d146680153.png)

Can focus text date entry and type something like "every! day starting next week" but that's cumbersome.

Suggest "d" for postpone to typed date.

**Comment by mgsloan** [comment]
`s` will select postpone.  I've updated the sheet to say this.  I realize that's not very mnemonic.  Perhaps `p` for postpone would be nice too.

`t p` seems like an appropriate key sequence for the times.  I've gone ahead and added that.

**Comment by mgsloan** [comment]
Released in version 76

**Comment by CJSF2323** [comment]
I may be missing something, but I don't see a way to postpone to a specific date. For example, if I wanted to postpone this task due today and every! week until 5/1, I'd have to type `every! week starting 5/1`

![image](https://user-images.githubusercontent.com/22968514/78146778-9feaab00-7400-11ea-894e-1eb9fb555146.png)

Would be great to press `t d 5/1` to accomplish that.

**Comment by mgsloan** [comment]
@CJSF2323 It's not quite as convenient as what you propose, but you can accomplish this with `T` followed by right-arrow, then space, then the date you want to postpone to.

**Comment by CJSF2323** [comment]
That sequence isn't working for me for some reason. Here's a video I
recorded <https://share.getcloudapp.com/xQugBbPJ> narrating me trying it.

**Comment by mgsloan** [comment]
Ah, thanks for sending a video, that definitely helps!

I should have been clearer, I wrote `T` but I should have written
`shift+t`.  This focuses the date / time editor.  The right arrow deselects
the contents of the editor and puts the cursor on the right hand side.

Does that work?  I know it's not ideal, but once I realized I could do that
I scrapped plans for having bindings that click the calendar (would be very
complex)

**Comment by CJSF2323** [comment]
Gotcha, thanks for the clarification. Still didn't work for me. Any idea
what I'm missing?

https://share.getcloudapp.com/4gumk1xB

**Comment by mgsloan** [comment]
Ahah, sorry, what I described doesn't work for me either, not sure why I
thought that worked.

I fiddled with it a bit, and discovered that if you type " starting 4/17"
after "every! month", it works.  Not great, but hopefully workable!

**Comment by CJSF2323** [comment]
Got it, that's where I ended up as well. Thanks!
