### ISSUE TITLE
Feature request: on/off button

### ISSUE THREAD

**Issue by kellyarwine** [mgsloan/todoist-shortcuts#115]
I notice select and drag no longer works with this extension is on.  Would just be great to be able to easily turn extension on and off when I need dragging at times.  (I'm assuming it's impossible or really challenging to allow for dragging and extensions, so clicking the extension in the Chrome toolbar to toggle on and off would be great).  Right now I have to open the extensions panel and turn it off which is a pain.

**Comment by mgsloan** [comment]
Hmm, it's possible that this is a feature I'm not familiar with.  For me, hovering the cursor over a task and dragging its drag handle on the left still works with the extension on.

**Comment by kellyarwine** [comment]
I was imagining something like Toggle extension where the feature is flipped off and on (changing the icon color) or a menu pops up with those options.  You're right, I was able to drag using your suggested approach, but it doesn't seem to be the native type of dragging and dropping?  For instance, I can't select multiple items and drag them all over.  Only one at a time.  It seems to operate weirdly with the extension on.

**Comment by mgsloan** [comment]
Curious!  I can't get dragging of multiple items to work.

Could potentially add a enable / disable thing to the toolbar, will keep this issue open to track maybe doing that.

**Comment by mgsloan** [comment]
Closing as wontfix.  Thanks for the suggestion!
