### ISSUE TITLE
Discussion of blockers for including todoist-shortcuts directly with Todoist

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#12]
In [this comment](https://github.com/rohitpaulk/todoist-tribute/issues/5#issuecomment-366739642), [Amir Salihefendic](https://github.com/amix) mentioned the idea of shipping todoist-shortcuts as part of Todoist.  I really like this idea, because currently only a handful of people use todoist-shortcuts.  By including it as part of Todoist, this can potentially benefit many more people.

There are two options for getting this into the production codebase:

1. Include it fairly directly.  This could actually be a decent approach - by dispatching events to DOM elements, I'm pretty much just calling functions in Todoist's code.  This does mean there is some boilerplate for finding these DOM elements.  It is kinda nice that it all fits in one file and nothing else needs to know about it.

2. Integrate it throughout Todoist's code.  Unfortunately, this would probably mostly be a rewrite.

I think the following are the main blockers:

* Only works with english version - see #2 - to fix, Todoist needs unique classes on the clickable DOM elements

* Extending the selection is extremely inefficient because Todoist's shift-click behaves a bit strangely #11 .  Turns out to not matter for reasonably sized lists, but I imagine it would be quite slow for large ones.

* This one is minor but an annoying regression I just noticed: #7

* Not sure how much of a blocker this is, but currently it only covers the free features.  See, for example, #3

I also opened https://github.com/mgsloan/todoist-shortcuts/issues/10 about how the performance of some parts could be improved if it was directly part of Todoist's code.

**Comment by amix** [comment]
@mgsloan Great write-up, I would recommend we go with 1) -- seems to be easiest

**Comment by mmazur** [comment]
As to how to ship keyboard support to users, there's also a third choice: in the settings menu just add a link to the chrome and firefox addons. My reasoning:

1. Power users will be able to get in on the action straight away. Some might want to help out with the github project being publicly accessible.
2. I suspect it'll be weeks/months before the extension and todoist internals are sufficiently in sync that there are no more known issues.
3. Ditto for the future set. Michael just lately became a premium user and I suspect he might have a different view on the full feature set in a few weeks time.
4. This way we completely circumvent the potential issue of "if todoist is shipping this, then how are new code uploads handled". Rapid development will be easier as a fully independent project.

And once the future set is stable, I think it'll be much easier to revisit the issue if a Todoist employee can just get a task to integrate it without having to worry that much about rapid changes.

**Comment by mgsloan** [comment]
Yup, I agree, @amix, including this rather directly seems like the best route.

@mmazur has a good point about there being some benefits to keeping todoist-shortcuts separate and opensource.

One option that I like would be to keep it opensource, but also including it directly in Todoist.  Perhaps I can transfer maintainership or co-maintain it with the Doist organization?  One reason I like shipping it with Todoist is shifting the primary responsibility for it.  I do not plan on spending a ton more time on it (unless paid to, that helps a lot ;) ), but in the meantime I do not mind spending a bit of time here and there maintaining it.

> I suspect it'll be weeks/months before the extension and todoist internals are sufficiently in sync that there are no more known issues.

Perhaps so, but there is not much to do for the currently known /bugs/.  There is certainly a lot to do before every useful UI action is wrapped.  I'm not sure if that should be the goal, I am mostly keen to wrap common actions.  It is ok to require the mouse for some of the more obscure stuff (e.g. not sure if there should be a way to collapse / expand nested projects).

**Comment by amix** [comment]
> One option that I like would be to keep it opensource, but also including it directly in Todoist.

+1 on this route. Also, we can compensate for the work involved here.

> I suspect it'll be weeks/months before the extension and todoist internals are sufficiently in sync that there are no more known issues.

I would also vouch for releasing a simple v1 with just the common actions. We can then add additional keys if a lot of users request it.

**Comment by mgsloan** [comment]
> +1 on this route. Also, we can compensate for the work involved here.

Awesome, that's great!  Thanks for your generosity in supporting such work

> I would also vouch for releasing a simple v1 with just the common actions. We can then add additional keys if a lot of users request it.

Yep, this makes sense to me.  Another reason to avoid having keybindings for every last thing is that then the documentation is larger and more intimidating, reducing the overall value of the keybindings.

I think there is a way to combat the problem of needing to memorize lots of keys, which is to show them directly in the UI.  One example of that is the `g` key bringing up letters next to everything you can switch to.  Similarly, I would like to annotate the different buttons in the scheduling popup with the key that is pressed to press that option.

If you've used the vimium / vimperator / pentadactyl browser extensions before, then the idea is a lot like that, except the keys you press tend to be mnemonic instead of arbitrary.  Well, the current project selection keys are pretty arbitrary.  I would like to make those smarter so that they are mnemonic when they can be.

**Comment by mgsloan** [comment]
As far as I can tell, all blockers are now resolved :)
