### ISSUE TITLE
Add other time trackers with 'shift+c'

### ISSUE THREAD

**Issue by fabiocpn** [mgsloan/todoist-shortcuts#121]
This is a feature request. 
I'm currently using clockify to perform time tracking. 

'Shift-Enter' activates and deactivates the time tracking in tasks that do not have a link. But I noticed that 'shift+c' is calling **togglButton**:
https://github.com/mgsloan/todoist-shortcuts/blob/6aea37facf4c7a37fbe89fe492bf20ddf39241a6/src/todoist-shortcuts.js#L745

Clockify uses two classes to activate timers:
'small clockify-button-inactive': to activate
'small clockify-button-active': to deactivate

I wonder if there is a way to make this more function more generic. I've done some tests myself (Sorry, I don't know any javascript - but the code is clear enough that I was able to make it work).

`    withUniqueClass(requireCursor(), ["small clockify-button-inactive","small clockify-button-active","toggl-button"], all, click);`
The line above seems to do the work and should keep the compatibility with toggl. I also don't see clockify buttons on the detailed view, so maybe this is the only change necessary? Of course, the name of the function could be changed throughout the script. I'm also not sure how this would impact other functions.

**Comment by mgsloan** [comment]
Hey, glad the code was clear enough to get something to work.  Thanks for sending specific details about how to make such an enhancement.

I've released version 79, which includes this patch, using code very similar to what you wrote.

Thanks!!
