### ISSUE TITLE
Feature Request: shortcut for moving a task to the top or bottom of a list

### ISSUE THREAD

**Issue by badiezadegan** [mgsloan/todoist-shortcuts#124]
It would be great if we could have shortcuts for moving tasks up to the top or down to the bottom of a list.  e.g.` Shift + Home` for moving to the top and `Shift + End` for moving to the bottom.

**Comment by mgsloan** [comment]
This is a good idea!  However, it's surprisingly hard to get it right.  Task movement is one of the trickiest and buggiest parts of todoist-shortcuts.

**Comment by mgsloan** [comment]
Closing this, as it's really tricky.  If these were normal keyboard shortcuts in an app, it'd be easy.  But todoist-shortcuts has to simulate user input events to turn keyboard shortcuts into actions.  Doing long range task moves correctly would involve both dragging the task and scrolling
