### ISSUE TITLE
bug: g shortcut for section navigation mode interferes with data entry

### ISSUE THREAD

**Issue by manogna4** [mgsloan/todoist-shortcuts#125]
I've definitely noticed this when quick adding a task. I press q to bring up quick add, and if I type g, then nothing happens. I need to type "g" twice to enter "g" into quick add.

It might be happening in other places too.

**Comment by mgsloan** [comment]
Curious, I don't see that happening.  I wouldn't be surprised if something fiddly is happening with keyboard events though.  Leaving this issue open for now

**Comment by uechoco** [comment]
I was in the same boat using todoist version 1000.
That time, I found some errors such as like "ItemSelecter.toggle is not a function" on Chrome console.
But the problem no longer reproduced after re-login.

**Comment by manogna4** [comment]
it's the same with "*". I can't seem to type an "*" in the task name when I quick add

**Comment by manogna4** [comment]
I realized I was seeing this because  I had 2 todoist keyboard shortcut extensions active 🤦‍♂️
this problem doesn't exist with "todoist-shortcuts". It exists with the other one.
Sorry for wasting your time. Do close the issue.

**Comment by mgsloan** [comment]
Ahah, that makes sense!  No problem
