### ISSUE TITLE
All selection bindings no longer work (x, *a, etc.)

### ISSUE THREAD

**Issue by GraphicThinkPad** [mgsloan/todoist-shortcuts#127]
Just noticed that I can no longer select tasks with `x`, nor can I select all tasks with *a. This is the case both on Brave and Chrome.

**Comment by GaryFurash** [comment]
Yes just noticed this.

**Comment by mgsloan** [comment]
Thanks for reporting!  Fixed in version 81

Todoist appears to have renamed `ItemSelecter.toggle` to `ItemSelecter.selectClick`.  This is a somewhat strange refactor as it still toggles.  But hey, it's working now.
