### ISSUE TITLE
Task view operations do not work for non-english localizations

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#131]
Similarly to #130, many of the task view buttons do not have disambiguating attributes, and so the buttons are being selected by matching on text that is locale-specific.  I believe they're working on this, so hopefully this can be fixed soon.

**Comment by thor** [comment]
Would a temporary alternative be to add localised dictionaries of how they're mapped for those users who submits them, or would you prefer to wait for them to add something identifiable to the action buttons?
I sent them a tweet, but I haven't heard anything back after they said they'd reach out to the developers, so I'm not sure if perhaps an (optimistic) support case might be better.

**Comment by mgsloan** [comment]
@thor I'd prefer to wait.  I've discussed it with some folks at Doist and my impression is that this will be improved, hopefully soon.

However, there is a workaround for individual users!  If you follow the instructions in https://github.com/mgsloan/todoist-shortcuts#how-to-customize-keyboard-shortcuts , you can use a modified version of the extension.  If you search the `todoist-shortcuts.js` file for `aria-label`, you will find the english strings being matched - these can be substituted with the labels from other languages.

**Comment by mgsloan** [comment]
Since most functionality is now broken for non-english Todoist, consolidating this into #137
