### ISSUE TITLE
"h" shortcut conflict - native todoist shortcut still active

### ISSUE THREAD

**Issue by Qu3cus** [mgsloan/todoist-shortcuts#134]
When I press the "h" key it jumps to the start page, which is the native todoist keyboard shortcut, rather than collapsing the selected task tree as it should.

Workaround: Use the left arrow key instead of h to collapse a task tree

**Comment by mgsloan** [comment]
Thanks for reporting!  I actually don't use task nesting much so didn't notice.  Fixed in version 84

**Comment by Qu3cus** [comment]
Wow! That was quick! Thanks so much for fixing this so promptly.
