### ISSUE TITLE
Not working on beta.todoist.com anymore?

### ISSUE THREAD

**Issue by stianmandarin** [mgsloan/todoist-shortcuts#135]
Is it just me? On todoist.com it works as before. On beta.todoist.com no features work anymore.

**Comment by mgsloan** [comment]
Not just you.  I'll take a look sometime soon, thanks for reporting!

**Comment by rich88** [comment]
I just upgraded to Version 1006 on production, and it seems like it's broken just about everything. :(

**Comment by mgsloan** [comment]
Things are working for me with version 1006.  Are you on the "Upcoming"
view?  Unfortunately that is known to be broken -
https://github.com/mgsloan/todoist-shortcuts/issues/110

**Comment by fabiocpn** [comment]
Shortcuts are also broken to me. Ironically it's **only** working (kind of working really) on the "Upcoming" view to me - at least I can see the blue indicator on the left side when I'm at the "Upcoming" view. Project view, inbox & today are not even showing the blue indicator.

**Comment by rich88** [comment]
ha, yes same here, it only works in Upcoming on v1006. in all other views, only g (go) and ? (help) work. 

funny enough, using beta.todoist.com v9160 (beta) it seems to work fine - so that's a workaround.

**Comment by manogna4** [comment]
the cursor movement functions aren't working for me in either  v9160 (beta) or v1006 in views other than 'upcoming'

**Comment by GraphicThinkPad** [comment]
I am experiencing the same after upgrading to version 1006: no blue cursor on any page except for the  "Upcoming" view.

**Comment by Qu3cus** [comment]
I'm experiencing the same thing on v1006, with a fresh todoist account, in a fresh chrome profile, so it doesn't seem to be due to any obvious incompatabilities (thought I'd check as mgsloan reported it working for them)

**Comment by stianmandarin** [comment]
> I'm experiencing the same thing on v1006, with a fresh todoist account, in a fresh chrome profile, so it doesn't seem to be due to any obvious incompatabilities (thought I'd check as mgsloan reported it working for them)
> 
> Edit: I'm on Windows 10, in case it's something platform specific

macOS here. I don't think it's OS related.

Confirming what others have already said, 1006 does not work. So now neither beta.todoist.com nor todoist.com works :( Todoist must have made some fairly big changes under the hood

**Comment by mgsloan** [comment]
I am now seeing this today too, which is weird because it wasn't happening for me with v1006

It looks like the new DOM changes that started in `Upcoming` have rolled out to the rest of the UI, and Doist developers did not add the classes I requested.  I have emailed them to let them know how unsatisfied I am with this.

I could put the work into to add a bunch of unsatisfying english-only hacks...  Oof

**Comment by stianmandarin** [comment]
> I am now seeing this today too, which is weird because it wasn't happening for me with v1006
> 
> It looks like the new DOM changes that started in `Upcoming` have rolled out to the rest of the UI, and Doist developers did not add the classes I requested a month ago to help fix #110. I have emailed them to let them know how unsatisfied I am with this.
> 
> I could put the work into to add a bunch of unsatisfying english-only hacks... Oof

Man what a bummer :( Todoist is soo slow to use without this plugin. Here's to hoping Todoist listens.

**Comment by mgsloan** [comment]
I've released a hacky workaround in version 85!  It only works on the english version of Todoist, and operations on the cursored task will cause the task to be selected.  A proper fix is tracked by #137, which should be feasible once Doist devs add the disambiguating classes.

**Comment by AndyHickman** [comment]
Dude 🤦‍♂️
Your plugin provides a good 50% of the value for this app. That is
disappointing to hear that they did not respond to your request.

**Comment by AndyHickman** [comment]
Good clarification 👍

**Comment by mgsloan** [comment]
Update: they intended to get this done much sooner but didn't get around to it.  Sounds like it's being prioritized now!

**Comment by mgsloan** [comment]
Update: The helpful folks at Doist added the disambiguating attributes to the DOM!  So now with todoist-shortcuts version 90, in the beta version of Todoist, the extension works for non-english locales :D
