### ISSUE TITLE
Not working on regular todoist /chrome

### ISSUE THREAD

**Issue by GaryFurash** [mgsloan/todoist-shortcuts#136]
For some reason as of this morning none of the extension keys work on chrome anymore (version 1006), latest Chrome, Windows 10. Tried reinstalling and uninstalling. Worked on Edge until I updated Todoist to latest version.

**Comment by mgsloan** [comment]
It looks like the new DOM changes that started in `Upcoming` have rolled out to the rest of the UI, and Doist developers did not add the classes I requested.

I could put the work into to add a bunch of unsatisfying english-only hacks...  Oof

**Comment by GaryFurash** [comment]
How do we escalate to get them just to buy and incorporate this? I've told them (as have others). Can we start a move-on-org?

**Comment by mgsloan** [comment]
Good question!  There was a discussion back in the day of incorporating it directly, but I haven't heard that mentioned anytime recently.

I've released a hacky workaround in version 85!  It only works on the english version of Todoist, and operations on the cursored task will cause the task to be selected.  A proper fix is tracked by #137, which should be feasible once Doist devs add the disambiguating classes.

**Comment by adamleerich** [comment]
@mgsloan Thanks for the quick fix on this!  I found *where* in the code (`getTaskById`?)the logic needed to change, but couldn't figure out how to fix it.  Next time maybe I'll be able to help.

**Comment by mgsloan** [comment]
You're welcome!  One nice consequence of these changes in Todoist is that a lot of conditional logic could get dropped in the extension to handle differences between project / today / upcoming views.

Certainly PRs are appreciated :)

**Comment by mgsloan** [comment]
Update: The helpful folks at Doist added the disambiguating attributes to the DOM!  So now with todoist-shortcuts version 90, in the beta version of Todoist, the extension works for non-english locales :D
