### ISSUE TITLE
Most functionality now only works for english version of Todoist

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#137]
I contacted Doist engineers about this a month ago, and they kindly offered to add the disambiguating classes.  Unfortunately, these disambiguating classes have not yet been added to the DOM.  This means that functionality must match on localization-specific text, namely english.

This issue tracks using those classes once they are added.

**Comment by mgsloan** [comment]
This issue also tracks removing the hack to select the cursored task before operating on it.

**Comment by Qu3cus** [comment]
Just wanted to document a bug/limitation with this hack, which is that the cursor will scroll (invisibly) through subtasks even if they are currently collapsed.

It's honestly not a big problem, and my guess is that it's not worth fixing in a temporary hack, but I thought it would be useful to at least have it documented.

Thanks for implementing the temporary fix so quickly - I'm really impressed with this level of responsiveness on a small, single-developer, free project.

**Comment by mgsloan** [comment]
@Qu3cus Thanks for reporting!  I didn't notice since I don't really use hierarchies of tasks much these days.  Fixed in version 90.

The helpful folks at Doist added the disambiguating attributes to the DOM!  So now with todoist-shortcuts version 90, in the beta version of Todoist, the extension works for non-english locales :D

**Comment by mgsloan** [comment]
Actually, going to just close this since the title is no longer accurate.  Tracking the code simplification concern elsewhere

**Comment by BrunoGomesCoelho** [comment]
Hi @mgsloan , on latest version (120) of todoist shortcuts, for both beta and non beta todoist, when I try to use bulk reschedule (* t), I'm getting the message:

> todoist-shortcuts bulk operations are disabled (hopefully temporarily). For more info, see issue #137.

I was wondering if this was the right issue to track this? Couldn't find a bulk operations issue;

I'm using the "English" language for todoist, although I have moved countries in the past year so there could be locale related bugs.

**Comment by mgsloan** [comment]
Good point Bruno, I think now these operations can be reinstated.  Noted
down a todo about it :)

**Comment by richardspiers** [comment]
Another vote for reinstating them please :)

**Comment by mgsloan** [comment]
Reinstated these in version 128, thanks for reminding me!
