### ISSUE TITLE
Adding Task via O or Shift O Only Opens Pop Up (which you can't click on)

### ISSUE THREAD

**Issue by GaryFurash** [mgsloan/todoist-shortcuts#139]
If on line and you use O or Shift-O I get this

![image](https://user-images.githubusercontent.com/15006133/84306947-11398f00-ab11-11ea-99c1-fbf1b6f8a628.png)

**Comment by llinfeng** [comment]
With `o` and `O`, recently (with version 129), I was prompted with two things in a project: a menu and a Quick Add Task box should pop up. Luckily, this only occurred with one specific project. I also see the same two boxes when I press `o` in any of the filters. It doesn't seem to matter how the filter is set.
![image](https://user-images.githubusercontent.com/5890407/121262626-750caa00-c882-11eb-9b63-7a446b892efa.png)

PS: I tried to create a copy of the project. Still, `o` or `O` should bring up both the popup menu and the Quick Add Task box. I needed to create a brand-new project to get normal behaviors from `o` and `O`.

@mgsloan If the same issue happens again with another project, is there a better way out? I understand `o` may not work with filters. Can I force the add-on to treat a project, well, like a project? A copy of the buggy project was having exactly the same issue: those two boxes should pop up when I press `o` (or `O`) when browsing tasks in the duplicate project.

**Comment by mgsloan** [comment]
Hmm, that's curious!  No idea what would cause this.  I haven't seen this
issue with any of my projects, so it's tough to fix.

You might consider creating a new project (possibly with a different name)
and moving the tasks to it.

**Comment by llinfeng** [comment]
Exactly, creating a new project solves the issue. Here is what I know per my tests: if `ProjectX` has the problem in [this post](https://github.com/mgsloan/todoist-shortcuts/issues/139#issuecomment-857204819), then
* A duplicated project of `ProjectX`, named as "Copy of ProjectX", will inherit the problem.
* Yet, creating another `ProjectX` with exactly the same name should "fix" the problem all together. It was still a manual process to move over all projects and subsections in the old project.
