### ISSUE TITLE
j/k navigation doesn't seem to work in Filters

### ISSUE THREAD

**Issue by svnsbck** [mgsloan/todoist-shortcuts#14]
Hi, first off thanks for this great extension, keyboard navigation is something that I wanted in Todoist since forever!
From my admittedly short usuage so far, I figured that j/k navigation doesn't seem to work within a Filter.

All the best.

**Comment by mgsloan** [comment]
Hi, thanks for the report.  I'm glad you appreciate the extension, I've also wanted keyboard shortcuts for quite a while.  It finally dawned on me that I could probably make it happen in the form of an extension.

The implementation of the cursor recently changed from being stored in todoist-shortcuts and displayed with a special style to instead using the drag handle, and leaving it up to Todoist to know which thing is focused.  A nice side effect of this is that you can use mouse hovering to change the focus.

Unfortunately, filters and labels do not allow you to use dragging to re-order.  So, this is not exactly trivial to fix.  Looks like it will require bringing back some of the code that keeps track of the cursor position within todoist-shortcuts.

**Comment by mgsloan** [comment]
This is finally fixed!! The fix is released with todoist-shortcuts version 13.
