### ISSUE TITLE
Move task keys not working (web, english)

### ISSUE THREAD

**Issue by GaryFurash** [mgsloan/todoist-shortcuts#141]
The movement keys don't work anymore

shift+j or shift+down | move task at cursor downwards
-- | --
shift+k or shift+up | move task at cursor upwards
shift+l or shift+left | dedent task at cursor
shift+h or shift+right | indent task at cursor

**Comment by mgsloan** [comment]
Thanks for reporting!  I actually don't use task motion much these days, so didn't notice the breakage.  My bad for taking a while to fix it, but now it's fixed in version 91
