### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by stianmandarin** [mgsloan/todoist-shortcuts#142]
`s`ort by date now adds a new section instead. Maybe a new key is in order?

**Comment by zsection** [comment]
hmm for me it does nothing. in fact none of the sorting shortcuts work for me. @mgsloan is this likely to be fixed soon? thanks very much

**Comment by shanness** [comment]
Yeah "s" does nothing for me either.  And the h (default home key) doesn't do anything either.

**Comment by mgsloan** [comment]
Fixed in version 105, though, the fix will only work in the english version of Todoist.
