### ISSUE TITLE
Label picker shortcuts are broken

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#143]
Ran into this today on todoist-shortcuts v90, on both beta and non-beta Todoist (weird?).
Typing **@**/**y** selects the task and pops up the multiselect toolbar at the top of the page, but it doesn't open the label picker.
Got this error: `Couldn't find unique descendant with tag button and passing predicate`.
All other shortcuts that access the multiselect toolbar work fine.

**Comment by mgsloan** [comment]
Thanks for reporting!  A bug in my updates making it work for locales other than english.  Fixed in version 91
