### ISSUE TITLE
C-key strange behaviour

### ISSUE THREAD

**Issue by EelkoL** [mgsloan/todoist-shortcuts#146]
When I hit the C-key in Chrome after loading the https://todoist.com/app/#start page, nothing happens. 
When I move the cursor by using the arrow keys, and then hit the C-key, nothing happens. 
When I move the cursor by using the mouse, and then hit the C-key, the comments open. 

I can not reproduce this on my laptop (W10) but I can reproduce this on my virtual work PC (W10) which I access through VMWare Horizon. Both on Todoist version 1010. Work PC on Chrome 81.0.4044.92, laptop on Chrome 83.0.4103.116

**Comment by nunes33** [comment]
> When I hit the C-key in Chrome after loading the https://todoist.com/app/#start page, nothing happens.
> When I move the cursor by using the arrow keys, and then hit the C-key, nothing happens.
> When I move the cursor by using the mouse, and then hit the C-key, the comments open.
> 
> I can not reproduce this on my laptop (W10) but I can reproduce this on my virtual work PC (W10) which I access through VMWare Horizon. Both on Todoist version 1010. Work PC on Chrome 81.0.4044.92, laptop on Chrome 83.0.4103.116


The same is happening to me.

**Comment by nunes33** [comment]
> When I hit the C-key in Chrome after loading the https://todoist.com/app/#start page, nothing happens.
> When I move the cursor by using the arrow keys, and then hit the C-key, nothing happens.
> When I move the cursor by using the mouse, and then hit the C-key, the comments open.
> 
> I can not reproduce this on my laptop (W10) but I can reproduce this on my virtual work PC (W10) which I access through VMWare Horizon. Both on Todoist version 1010. Work PC on Chrome 81.0.4044.92, laptop on Chrome 83.0.4103.116

![image](https://user-images.githubusercontent.com/68063592/87039720-fb79c100-c1c5-11ea-9671-178555bf5782.png)

Press ic. Worked fine for me ;)

**Comment by GraphicThinkPad** [comment]
This is happening with me too on Brave 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit).

`ic` works for me too, but I sure would love the regular `c` shortcut back.

**Comment by mgsloan** [comment]
Thanks for reporting!  Fixed in version 93

Looks like Todoist now defers creation of some of the action buttons, until mouse hover, so the button for comments didn't exist.  I didn't manage to simulate a hover in a way that triggered this behavior.  However, it turned out that simply opening the task view and then navigating to buttons, very similar to the `ic` workaround, did the trick :)
