### ISSUE TITLE
Task scheduler is broken in Beta

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#149]
Found this in beta version 7184.
The **t/T** keys don't work anymore. Here's the stacktrace:

![scheduler](https://user-images.githubusercontent.com/40349450/87836016-96684000-c843-11ea-9bcd-d1b7c274b179.png)

**Comment by mgsloan** [comment]
Ah, curious, thanks for reporting!  Looks like sending a `mouseenter` event to the task is no longer causing it to lazily populate the action buttons.  I haven't been able to figure out what event to send to the task, so have emailed Todoist developers about it.

**Comment by mgsloan** [comment]
Looks like this landed on main todoist.  The suggestion from a Todoist developer was to send a mouseover event, and indeed once I sent one of those with some options set, it worked! 

Fixed in version 99
