### ISSUE TITLE
Selection shortcut ('x') triggers when using input field

### ISSUE THREAD

**Issue by rohitpaulk** [mgsloan/todoist-shortcuts#15]
**Steps to replicate**:

- Press 'o' to add a new task below any other
- Enter any text that contains x

**Expected**: Selection shortcut doesn't trigger
**Actual**: Selection shortcut is triggered

![xselectioninput](https://user-images.githubusercontent.com/3893573/36668817-85a7b0a0-1b18-11e8-9101-3ca52cd89e3e.gif)

<hr/>

Thanks for the great work, @mgsloan :) I just started using this today, and it is **SO** useful. Can't wait for this to officially land in Todoist.

**Comment by mmazur** [comment]
Yup, was about to write the same report, just noticed this myself with current git master head.

**Comment by mgsloan** [comment]
Thanks for the report!  I guess since the switchover to the new behavior
for "x", I haven't had many todo tasks to order xylophones or feed the
axolotls :)

Will hopefully address this soon, but currently rather busy.

**Comment by mgsloan** [comment]
Fixed!
