### ISSUE TITLE
`a` and `A` seem to get swallowed by todoist-shortcuts

### ISSUE THREAD

**Issue by GraphicThinkPad** [mgsloan/todoist-shortcuts#150]
The bottom line is that neither `a` nor `A` work inside projects. I understand that these shortcuts are native to Todoist, but it appears that todoist-shortcuts is catching these keys somehow and is doing nothing since there's no function inside the application to handle `a` and `A`.

Todoist 1019. Version 83.0.4103.116 (Official Build) (64-bit)

**Comment by mgsloan** [comment]
Thanks for reporting!  Should be fixed in version 103
