### ISSUE TITLE
V shortcut just opens pop up [Chrome, Todoist v 1020]

### ISSUE THREAD

**Issue by GaryFurash** [mgsloan/todoist-shortcuts#151]
It used to go to the move project dialog

![image](https://user-images.githubusercontent.com/15006133/90417690-f29fc900-e068-11ea-8cb5-38ed14c86df0.png)

**Comment by AndyHickman** [comment]
save us, Michael! :)

**Comment by mgsloan** [comment]
Thanks for reporting, my browser's Todoist was still on v1019, so I didn't notice.  Fixed in version 104.
