### ISSUE TITLE
Bug: In task view pressing "t r" doesn't remove due date as expected

### ISSUE THREAD

**Issue by Qu3cus** [mgsloan/todoist-shortcuts#152]
In a project view, or today, upcoming etc. pressing "t" and then "r" removes the due date as documented. When viewing an individual task however pressing the same keys just puts an "r" character into the due date text entry box.

This is obviously a minor bug and not a big deal, but it does trip me up every so often, so I thought I'd report it.

Thanks!

**Comment by mgsloan** [comment]
Thanks for reporting!  I've noted it down in my todos :)  Should be a straightforward fix, probably will do it this weekend.

**Comment by mgsloan** [comment]
Fixed in version 107!
