### ISSUE TITLE
Can't move tasks around with shortcuts on Today view

### ISSUE THREAD

**Issue by josian** [mgsloan/todoist-shortcuts#153]
I used to be able to do this.  I can actually still do it if I use the mouse.  But now seems the keyboard shortcuts don't work because it's considered "filtered mode".

To replicate:

1. Go to Inbox view
1. Select any single task (either by hovering or via j/k keyboard shortcuts)
1. Press Shift + J or Shift + K to try to move the task up or down.
1. You should see a message in the console saying: "todoist-shortcuts: Moving task up does not work in filter mode. (this is fine)".

But I think it's not fine.  If I remember correctly, this used to work.  And it was powerful because I could quickly re-sort things I was about to tackle that day.

Looks like the issue is related to the Today's view `viewMode` to be considered "agenda".
https://github.com/mgsloan/todoist-shortcuts/blob/d19df427a2bd571abd14712d632274d1cc011c98/src/todoist-shortcuts.js#L2039-L2044

Perhaps there is a need for an extra `viewMode` to distinguish filter mode from agenda mode?
https://github.com/mgsloan/todoist-shortcuts/blob/d19df427a2bd571abd14712d632274d1cc011c98/src/todoist-shortcuts.js#L3443-L3450

**Comment by mgsloan** [comment]
Thanks for reporting, fixed in version 108!
