### ISSUE TITLE
'd'one doesn't seem to work after update to 1036

### ISSUE THREAD

**Issue by cnxguy** [mgsloan/todoist-shortcuts#154]
The d key for marking an item as done stopped working when I upgraded to 1036. Was working fine in 1035. Tried both chrome and chrome edge.

**Comment by mrderiuzz** [comment]
I was about to open the same issue. It's also broken for me. I suppose it's probably related to the checkbox changes:

> ⚙️ Check off your tasks a bit easier now that the checkbox is a touch larger. ✔️
https://get.todoist.help/hc/en-us/articles/115005442125-Todoist-for-Web-Changelog

**Comment by cnxguy** [comment]
Yeah - that's what I figured too, looked like a strong candidate at least.
