### ISSUE TITLE
archive function; permanently done button

### ISSUE THREAD

**Issue by galantra** [mgsloan/todoist-shortcuts#155]
In the readme, e has been assigned to "delete" (which I can confirm is its function now). However, the text below the table still states:

> Archiving a task via e is fairly similar to marking it complete via d. Here are the differences:
> 
>     If the task is a child task, if you "Complete" it it will be checked and greyed out (and will remain in the list under the uncompleted parent task until the parent task is completed). If you "Archive" the child task it will be checked and then removed from view.
> 
>     If the task is a Recurring Task (e.g. every day) and you "Complete Task" it will be scheduled for the next date of recurrence. If you "Archive Task" it will be completed and not recur again.
> 

I'd suggest to update this text.

Furthermore, I suggest to have a button that marks recurrent tasks as _permanently_ done.

**Comment by mgsloan** [comment]
Good catch!  Thanks for opening the issue.  I've updated the readme text
