### ISSUE TITLE
"section navigation" only working for favorite projects/labels/filters

### ISSUE THREAD

**Issue by sonofhypnos** [mgsloan/todoist-shortcuts#157]
The navigation for different sections has stopped working except for labels and filters that aren't in favorites. I am using the beta version 1043 of the browser app in google chrome.

**Comment by sonofhypnos** [comment]
![grafik](https://user-images.githubusercontent.com/46806445/98483897-03954c00-220c-11eb-88a2-d26ca482b4bf.png)

**Comment by mgsloan** [comment]
Thanks for reporting!  I believe this is fixed in version 113
