### ISSUE TITLE
More efficient task selection

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#158]
It would be good to have a more efficient way to select tasks ala `ItemSelector`, which resolved #11, but was recently removed from Todoist.

Currently, after finding a proper resolution for #156, every selection change causes a deselection followed by re-selecting the tasks using a carefully orchestrated series of shift-clicks.

**Comment by mgsloan** [comment]
Ahah, based on helpful feedback from a Todoist developer, I switched this over to just using ctrl+click, which I did not realize existed.

**Comment by GraphicThinkPad** [comment]
Not sure if I should open a new issue, so I'm replying to you here. I'm on a Mac, and hitting `x` now has the same effect as hitting `i` on a task. Perhaps this is because on Mac, it's `cmd` + `click` that selects multiple tasks?

**Comment by mgsloan** [comment]
GraphicThinkPad@  Ah I see, darn!  Is there a way on mac to toggle the
selection state of a task using keyboard and mouse?

**Comment by GraphicThinkPad** [comment]
My bad, that's what I was trying to say in my reply. On Mac, toggling the
selection state of a task is done by hitting `cmd` + `click` as opposed to
Windows/Linux' `ctrl` + `click`.

**Comment by mgsloan** [comment]
Version 115 attempts to fix this on Mac by setting "metaKey: true" instead
of "ctrlKey: true".  I don't have a mac to test it with, so please let me
know if that fixed it.

**Comment by GraphicThinkPad** [comment]
Success! `x` now selects properly.

**Comment by mgsloan** [comment]
Woohoo, thanks for verifying!

**Comment by gregratliff** [comment]
Thank you for that fix!!!
