### ISSUE TITLE
Shortcut for selecting all tasks and clearing all selected tasks doesn't work

### ISSUE THREAD

**Issue by ClydeRomo** [mgsloan/todoist-shortcuts#16]
Tested in Firefox 

![Alt text](https://cl.ly/1H2D0I3M0P3J/Image%202018-03-17%20at%2011.24.42%20AM.png)

**Comment by mgsloan** [comment]
@ClydeRomo Hey, sorry for the delay.  Both of these shortcuts work for me in both chrome and firefox.  Is it possible that some other browser extension is intercepting the keyboard events and preventing these from working?

**Comment by ClydeRomo** [comment]
Maybe I'm using it wrong 🤔

* If I press `x` then `1`, it sets my priority to **P1**
* If I press `x` then `a`, nothing happens. Am I doing it properly? I'm not quite sure if this is how it should work.

**Comment by rohitpaulk** [comment]
@ClydeRomo The `*` literally means `*` 😃 This is similar to the Gmail shortcuts: 

![screen shot 2018-04-09 at 12 19 36 am](https://user-images.githubusercontent.com/3893573/38471233-b6b4750a-3b8b-11e8-8d16-f8007b42eac4.png)

**Comment by mgsloan** [comment]
Yes, it's literally `*`, aka `shift + 8`.

**Comment by ClydeRomo** [comment]
Thanks! Make sense ... 🤦‍♂️
