### ISSUE TITLE
Version 1054 Broken Scrolling?

### ISSUE THREAD

**Issue by silentjay** [mgsloan/todoist-shortcuts#163]
Browser: Brave Version 1.17.73 Chromium: 87.0.4280.67 (Official Build) (64-bit) 

Using 'j' and 'k' to move up and down the items list no longer results in the browser scrolling to keep the current item in view e.g. keep pressing 'j' past the last visible item and the browser will not scroll the new ones into view. Was working up until today.

I need to do some more testing to make sure I've not somehow messed up my browser config but seems like a coincidence that todoist released a new version yesterday.

Not sure if relevant but do see this warning msg in the console:

```
todoist-shortcuts: Couldn't find ID page_background 
Error
    at getStack (chrome-extension://dehmghpdcahlffompjagejmgbcfahndp/todoist-shortcuts.js:3519:13)
    at warn (chrome-extension://dehmghpdcahlffompjagejmgbcfahndp/todoist-shortcuts.js:3502:22)
    at withId (chrome-extension://dehmghpdcahlffompjagejmgbcfahndp/todoist-shortcuts.js:3602:7)
    at updateBackgroundColor (chrome-extension://dehmghpdcahlffompjagejmgbcfahndp/todoist-shortcuts.js:4023:5)
    at chrome-extension://dehmghpdcahlffompjagejmgbcfahndp/todoist-shortcuts.js:4040:3
```

**Comment by silentjay** [comment]
No idea if there's been a new release of todoist or todoist-shortcuts or something my end but scrolling is now working again as expected.

**Comment by mgsloan** [comment]
Oh yeah I forgot to mention I fixed this in version 117 :)

Thanks for reporting the issue!  These days my workflows don't typically involve viewing more than a screenful of tasks, so I hadn't noticed.

**Comment by silentjay** [comment]
No probs, thanks for the quick fix.
