### ISSUE TITLE
Manipulating Sections

### ISSUE THREAD

**Issue by albert239825** [mgsloan/todoist-shortcuts#164]
Hey, I want to use sections to organize my tasks within a project, is there a way to have short cuts for expanding and collapsing sections. Also, the shortcuts with and * like * + a to select all don't work for me. Is there something I'm doing wrong? Thanks!

**Comment by mgsloan** [comment]
`* a` should work.  Are you pressing `*`, releasing, and then pressing `a`?

There are not shortcuts for expanding and collapsing sections, sorry.  I
don't personally use sections, and these days I don't have much time for
todoist-shortcuts beyond fixing bugs.  I'd probably accept a PR for it.

-Michael

**Comment by albert239825** [comment]
Thank you so much for the response. My current understanding of the asterisk shortcuts is to press shift + 8 + key (ex a) to activate the shortcut. Am I wrong? Thank you.

**Comment by mgsloan** [comment]
I think so, sounds like you are pressing all of the keys at once.  Instead,
press shift+8 first, release, and then press `a`.  Sorry for the ambiguity,
I suppose such key sequences are not so common outside of programs like vim
or emacs

**Comment by albert239825** [comment]
yes, that worked! Thank you so much. Sorry for my lack of knowledge with vim. I'm a baby coder trying to transition from eclipse to vs code for more versatility and have never touched vim. I really appreciate the help. Enjoy the rest of your holidays.

**Comment by mgsloan** [comment]
You're welcome!  Noted this down to maybe make the docs clearer about this
in the future
