### ISSUE TITLE
navigateToTask (G) doesn't work on tasks inside sections

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#169]
(See #144 about navigateToTask not working in filter view. This issue pertains to label view, where navigateToTask mostly works.)

Pressing `G` on a task that's inside of some section produces this [error](https://github.com/mgsloan/todoist-shortcuts/blob/master/src/todoist-shortcuts.js#L943) ("couldn't find project button").

I'm guessing that's because Todoist [v1063/1064](https://todoist.com/help/articles/todoist-for-web-changelog) (~3 weeks ago) changed the project name for such tasks to display as `proj / section` instead of just the project name. If so, the fix could be to just grab the part before the slash as the project name and navigate to that.

**Comment by mgsloan** [comment]
Thanks for reporting!  Fixed in version 125
