### ISSUE TITLE
fix/remove dead link in readme.md

### ISSUE THREAD

**Issue by gregsadetsky** [mgsloan/todoist-shortcuts#17]
at the very end of `readme.md`, there is a link to "See this github thread" which leads to a dead url:

https://github.com/rohitpaulk/todoist-tribute/issues/5

**Comment by rohitpaulk** [comment]
Yh, I removed the issues tab from that repo as it was intended as just a showcase. Please let me know if you'd like to copy paste content from the original issue :)

**Comment by gregsadetsky** [comment]
ha, yeah, whatever works! as long as we find a way to get rid of the dead link in the readme haha :-)

**Comment by mgsloan** [comment]
Thanks for noticing and mentioning it. I've updated the readme
