### ISSUE TITLE
navigateToTask (G): "Couldn't find cursored task after switching to its project"

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#170]
(See #144 about navigateToTask not working in filter view. This issue pertains to label view, where navigateToTask mostly works.)

It correctly switches to the project containing the task and briefly highlights/blinks the task, but doesn't put the cursor on the task. I have no hunch on this one. :-)

**Comment by mgsloan** [comment]
Thanks for reporting!  Fixed in version 125
