### ISSUE TITLE
shortcuts for favorite filters don't work after the update

### ISSUE THREAD

**Issue by mrderiuzz** [mgsloan/todoist-shortcuts#174]
after the newest todoist web update, todoist-shortcuts "don't see" favorite filters and thus no shortcuts are generated for them:

![image](https://user-images.githubusercontent.com/24499888/107490352-12342c00-6b8a-11eb-9ec2-2b2127e0a269.png)

**Comment by mgsloan** [comment]
Fixed yesterday in version 127 (see also #173), if it's still not working you may need to take action to update the extension
