### ISSUE TITLE
Shortcut to sort Projects, Labels, or Filters in the side panel?

### ISSUE THREAD

**Issue by error9900** [mgsloan/todoist-shortcuts#175]
No clue if this is possible, but I like having my Projects, Labels, & Filters in alphabetical order in the side panel, and it's really annoying that I have to tediously do this manually every time I add or rename one of them...

Thanks for a great extension, otherwise!

**Comment by mgsloan** [comment]
Hey, thanks!  Glad you appreciate the extension!

I don't think such a feature is within the scope of todoist-shortcuts, though, so closing this feature request as "wontfix".  If only I had infinite time for all the things!
