### ISSUE TITLE
Moving up and down via shortcuts does not work in Firefox

### ISSUE THREAD

**Issue by matejdro** [mgsloan/todoist-shortcuts#176]
When attempting to move task up or down via Shift + Up/Down/j/k, task will just blink in place, but will not move.

This is with Firefox  87.0 and todoist shortcuts 128.

**Comment by mgsloan** [comment]
Hmm, have you removed sorting from the project?  When sorting is enabled,
task movement doesn't work.

For me task movement works in firefox

**Comment by matejdro** [comment]
I can move tasks with mouse with no problems, so it's not the sorting.

**Comment by matejdro** [comment]
Are there any logs or anything else I can give you to help sort out the issue?

**Comment by mgsloan** [comment]
If you download the extension code, and then set `DEBUG` to true here -
https://github.com/mgsloan/todoist-shortcuts/blob/master/src/todoist-shortcuts.js#L5
- then load the modified extension you will get a lot more logs.  Not sure
if they will help diagnose, but they might!

It might not be necessary to enable the DEBUG logging.  By default it will
still log errors, so the normal logs in developer tools might also be
useful.

**Comment by matejdro** [comment]
Huh it seems to work now. Maybe it was an update from Todoist that messed up something before. Thanks for your help.

**Comment by matejdro** [comment]
This is still happening, but only in one project (can't find anything different in that project). Here is the debug log of me trying to move a task up with Shift + K:

```
todoist-shortcuts: keydownHandler 
keydown Shift { target: body.with_new_emoji_sizing
, key: "K", charCode: 0, keyCode: 75 }
vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.242 todoist-shortcuts: ignoring scroll vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.242 todoist-shortcuts: moveUp target is 
<li id="task-4751098710" class="task_list_item task_list_item--project_hidden" data-selection-id="4751098710" aria-selected="false" data-item-id="4751098710" data-item-indent="1" style="">
vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.261 todoist-shortcuts: viewMode =  project vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.262 todoist-shortcuts: ignoring mutations since drag is in progress: 
Array [ MutationRecord ]
vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.267 todoist-shortcuts: handleMouseMove ignoring synthetic mouse move event. 11 vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.332 todoist-shortcuts: restoring scroll vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.332 todoist-shortcuts: Checking if cursor still exists: 4751839266 indent_1 vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.333 todoist-shortcuts: Cursor hasn't changed task: currentSection =  <empty string> lastCursorSection =  <empty string> id = 4751839266 indent = indent_1 vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.333 todoist-shortcuts: Found normal cursor, so storing its context vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.333 todoist-shortcuts: wrote down cursor context: id = 4751839266 indent = indent_1 section = <empty string> idx = 31 vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.350 todoist-shortcuts: viewMode =  project vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.351 todoist-shortcuts: ensuring cursor due to mutations: 
Array [ MutationRecord ]
vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.351 todoist-shortcuts: Checking if cursor still exists: 4751839266 indent_1 vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.351 todoist-shortcuts: Cursor hasn't changed task: currentSection =  <empty string> lastCursorSection =  <empty string> id = 4751839266 indent = indent_1 vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.352 todoist-shortcuts: Found normal cursor, so storing its context vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.352 todoist-shortcuts: wrote down cursor context: id = 4751839266 indent = indent_1 section = <empty string> idx = 31 vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.400 todoist-shortcuts: Checking if cursor still exists: 4751839266 indent_1 vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.401 todoist-shortcuts: Cursor hasn't changed task: currentSection =  <empty string> lastCursorSection =  <empty string> id = 4751839266 indent = indent_1 vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.401 todoist-shortcuts: Found normal cursor, so storing its context vendor.f3cab33e857221b9f96a.js:1:366360
07:56:42.401 todoist-shortcuts: wrote down cursor context: id = 4751839266 indent = indent_1 section = <empty string> idx = 31 vendor.f3cab33e857221b9f96a.js:1:366360
```

**Comment by GaryFurash** [comment]
Same issue - in Inbox w/ no sort enabled in chrome. none of the move lines work. Works with edge for some reason.

**Comment by mgsloan** [comment]
Curious!  The only browsers available to me are chrome and firefox, so I
can't straightforwardly work on this.  Would accept patches fixing it
though, naturally!

**Comment by matejdro** [comment]
> The only browsers available to me are chrome and firefox, so I can't straightforwardly work on this.

Well, I'm having issue in Firefox and @GaryFurash has an issue in Chrome, so I don't think this is an issue ;) 

Any chance you could make a branch with more logging enabled? That way I can install this and give you more logs on what is going on.

**Comment by mgsloan** [comment]
True!

To get more logs you can change line 5 from `const DEBUG = false;` to
`const DEBUG = true;`

-Michael

**Comment by matejdro** [comment]
I've given you debug logs above. Or do you want me to retry this with newer builds (maybe you added more logging statements?)?

**Comment by mgsloan** [comment]
Sorry, since I have no idea how to reproduce the bug, I can't really work on fixing it.

**Comment by matejdro** [comment]
Right, but we can reproduce it for you and give you all the necessary data to fix it.

**Comment by llinfeng** [comment]
I, too, have trouble using `j/k` to move around. I suppose this is mostly due to the new Todoist shortcut thing. I just wrote to their tech support, asking if they have an option to undo all their own shortcuts like what Gmail has been offering for almost 10 years.

**Comment by matejdro** [comment]
@mgsloan I've been trying to debug it and the issue appears to be in the  `offset` method. Sometimes, offset methods does not appear to provide proper Y for the emulated mouse cursor (it is hundreds off) and it thus attempts to move it to a different position.

Changing offset method to the following code fixes the shifting issue:

```code
  function offset(el) {
    let bounds = el.getBoundingClientRect();
    return {x: bounds.x, y: bounds.y};
  }
```

however, it causes different issues (just moving up or down with j and k causes page to randomly scroll around). 

Do you have any idea what could cause the offset method to break? I can try inserting extra debug statements.

**Comment by mgsloan** [comment]
Fix will be in version 142!  Thanks matejdro!

I can now reproduce this issue.  The problem happens when there are enough tasks in a project to allow scrolling, and the window is scrolled down.

I've kept the "put task in view" code using the old implementation of offset, and used matejdro's offset code for task movement.

**Comment by matejdro** [comment]
That's amazing, thanks a lot.
