### ISSUE TITLE
Sync hotkey not working

### ISSUE THREAD

**Issue by einnocent** [mgsloan/todoist-shortcuts#178]
Doing `ctrl+s` does not sync.  "Last updated" is reported as 22 hours ago before and after use of hotkey, and list of items does not change even though they are known to have changed. 

Further, network tab in web developer toolbar shows no network activity. A JS warning does however appear and is pasted below:

![image](https://user-images.githubusercontent.com/356718/120083250-3a359580-c07c-11eb-904d-879990c12292.png)

This is for:
OS: OSX 10.15.7 (Catalina)
Browser: Chrome 90.0.4430.72
Extension version: 129

**Comment by mgsloan** [comment]
Ah, thanks for letting me know!  Fixed in version 131
