### ISSUE TITLE
Consider removing references to the Todoist Smart Scheduler

### ISSUE THREAD

**Issue by ErikOsterud** [mgsloan/todoist-shortcuts#179]
I just noticed that this is documented in todoist-shortcuts and available as a shortcut, but the Smart Scheduler functionality was removed from Todoist a while ago (just over a year ago I think?) with the reasoning:
_"Unfortunately we had to remove this feature due to its complexity in development and maintenance and the fact that it was almost never used :("_

**Comment by mgsloan** [comment]
Ah, good catch!  Version 130 comes with a fix for this.
