### ISSUE TITLE
Add support for expand/collapse all task 

### ISSUE THREAD

**Issue by ClydeRomo** [mgsloan/todoist-shortcuts#18]
@mgsloan Thanks for the awesome work! This is one of the things I miss. 

The keyboards shortcuts are really useful and powerful. Thanks for developing it 😊

**Comment by mgsloan** [comment]
@ClydeRomo Glad they are useful to you!  This is a good idea.  I've implemented it, just took ~20 minutes.

**Comment by ClydeRomo** [comment]
I just tried this. It seems that it only expands/collapse the currently selected tasks (similar to how h or l works). Is this by design? 🙂

**Comment by mgsloan** [comment]
It should expand / collapse all tasks in the current view.  Are you using the latest master version?  A new version of todoist-shortcuts hasn't been released yet.

**Comment by ClydeRomo** [comment]
Yes, I'm using the latest. It's likely I don't have the latest version then 😅

Thanks again!
