### ISSUE TITLE
Turn off built-in Todoist shortcuts

### ISSUE THREAD

**Issue by adamleerich** [mgsloan/todoist-shortcuts#184]
Creating this issue as a placeholder for a new feature requested in #180.  I was going to assign it to myself and label it as "feature request" but I don't think I have rights to do that.

Goal: disable Todoist built-in shortcut keys.  But, allow user to set this as an option instead of making it the default behavior.

**Comment by jakelfreeman** [comment]
Yes please! v1446 completely broke this extension and the new native shortcuts are on the whole much worse than the extension. Several features that I miss dearly.

**Comment by markvankampen** [comment]
I ran into the same issue today when I updated to Todoist v1446. Broke my workflow of just typing `t t` to postpone a task to tomorrow or `t c` to set the due date to today.

**Comment by EelkoL** [comment]
Yes please! I think Todoist should implement the Todoist-shortcuts, as now it is very confusing. Turn off the built-in Todoist shortcuts is an option as well.

**Comment by loganyeang** [comment]
yeah me too. can't use any shortcuts now, after recent update (I think the update is the reason like you guys)

**Comment by mgsloan** [comment]
Fixed in version 134!

Keyboard handling now no longer falls through to Todoist's key event handler.  I think this might break some shortcuts that rely on this fallthrough, but I don't recall what.  Will hopefully revisit this in more detail soon, but wanted to get the rough fix out ASAP.

**Comment by mgsloan** [comment]
Version 135 fixes all the shortcuts broken by the hasty fix.

> Specifically, this fixes `q` (quick add), `m` (toggle left nav), `p` (sort by priority), `n` (sort by name), `r` (sort by assignee), and `f` / `/` (focus search) by directly implementing these via simulating mouseclicks (like the rest of todoist-shortcuts).

So, now todoist-shortcuts is doing all of the keyboard handling (except when text inputs and such are involved).  So I consider this resolved!

**Comment by jakelfreeman** [comment]
Godsend! Thank you so much, Michael!

**Comment by kory-smith** [comment]
You are, unequivocally, the man.
