### ISSUE TITLE
Move task at cursor using shift up/down doesn't work in Chrome

### ISSUE THREAD

**Issue by joshdoyle** [mgsloan/todoist-shortcuts#185]
I just installed this extension and moving task at cursor using shift up/down doesn't work. The screen flickers but doesn't move the task. I'm using Chrome Version 95.0.4638.69 (Official Build) (x86_64) on a Mac and version 136 of the extension.

**Comment by mgsloan** [comment]
Have you tried task motion in projects?  Some views (sorted views, labels, etc) don't support task motion
