### ISSUE TITLE
Add-on interferes with the new Command Menu shortcut (Ctrl-K)

### ISSUE THREAD

**Issue by capi** [mgsloan/todoist-shortcuts#186]
Todoist introduced the new command menu (Ctrl-K) shortcut. As long as this extension is installed, the Ctrl-K is unfortunately not working on Windows 10, Firefox 94.0.1. Instead, the unified search bar pops up in Google search mode.

![image](https://user-images.githubusercontent.com/254852/141421034-3b59b94d-bca3-4922-a418-e6a9d54dd873.png)

**Comment by mgsloan** [comment]
Fixed in version 138!

**Comment by capi** [comment]
Thanks a lot!
