### ISSUE TITLE
Bulk add/remove label issues

### ISSUE THREAD

**Issue by jakelfreeman** [mgsloan/todoist-shortcuts#187]
Bulk adding/removing labels from tasks has always been finicky for me, but even moreso recently. I typically select either with a combination of [x] and arrow keys or with a bulk selection (e.g., [*] + [a]) and then hit [@]" to open the label menu, and make my selection(s). All of that runs smoothly--the issue is when I go to close the label menu, either with [ESC] or by clicking outside the menu bar, oftentimes the new label selections aren't applied. Is anyone else having this issue? Is there a different way to close the label menu that is more likely to succeed?

**Comment by mgsloan** [comment]
I'm not seeing this issue, label changes seem to work well.  Perhaps there was a todoist bug that has now been fixed?  Please re-open if you are still seeing the problem.
