### ISSUE TITLE
Add functions / shortcuts to get URL and title from current task (under cursor)

### ISSUE THREAD

**Issue by mdbraber** [mgsloan/todoist-shortcuts#189]
It would be nice if we could select and copy URLs and titles from the current task under the cursor. This is also helpful with external scripting like the macOS app I'm building that wraps Todoist in Webview and also offers AppleScript support. It works with functions like below. This also is (partly) present in the current Todoist keyboard shortcuts as "Copy link to task" (Command-Shift-,). Would it be possible to integrate this and maybe even add a shortcut to it?

```
  // Get the URL for the task under the cursor
  function getCursorUrl() {
    return "https://todoist.com/showTask?id=" + getTaskId(requireCursor());
  }

  // Get the title for the task under the cursor
  function getCursorTitle() {
    const classes = ['content', 'task_content'];
    let result
    withUniqueClass(requireCursor(), classes, all, (content) => {
        result = content.innerText;
    });
    return result
  }
```

**Comment by jakelfreeman** [comment]
This isn't the ideal solution, but as a bridge... I created a macro via KeyboardMaestro for doing just this. See attached for a copy of the macro, probably need to tweak it before it works for your purposes as I built this just for my own personal use. I imagine you can do something similar with AHK or another macro program if you prefer.
[Get Task Email.kmmacros.zip](https://github.com/mgsloan/todoist-shortcuts/files/7840617/Get.Task.Email.kmmacros.zip)

**Comment by mdbraber** [comment]
Thanks @jakelfreeman. It would be nice though if we could add these functions as they're pretty straightforward and would allow a more robust solution.

**Comment by mgsloan** [comment]
Included in version 139!

    * `ctrl+c` - copy title and url of task in markdown format
    * `ctrl+,` - copy task title
    * `ctrl+shift+,` - copy task url

**Comment by jakelfreeman** [comment]
Would it also be possible to do this for the "add comments via email" option (feel free to split this into a separate open item)?

**Comment by mgsloan** [comment]
Oh interesting I didn't know about email-to-comment.  It'd be possible, but
a bit tricky to add because it seems like the comments email address is
only available via a context menu on the task info page.  I'd accept a PR
adding such functionality!
