### ISSUE TITLE
Unclear: How to use the Schedule commands

### ISSUE THREAD

**Issue by jmenzler** [mgsloan/todoist-shortcuts#19]
I'm not sure how to use the default selection commands - Pressing `* + a` (with Shift involved, German keyboard) does not select all tasks for me. 

How are these command supposed to be triggered?

**Comment by mgsloan** [comment]
You press and release the `*` key, and then you press and release the `a` key.  Should work, would be interesting if it doesn't.

**Comment by jmenzler** [comment]
Thanks! I got it to work, no bugs! 👍🙂
