### ISSUE TITLE
Enhancement: Shortcut to pick a random task in a currently opened view?

### ISSUE THREAD

**Issue by antois** [mgsloan/todoist-shortcuts#190]
Hi there, thanks for the great extension. I'd like to propose an enhancement: add a shortcut to open a random task in a given view. It sometimes helps to use something like this to start off working on tasks. 

I saw a discussion of a similar solution on Reddit (1) but it's dated and the proposed solutions seem to not working. What do you think?

(1) https://i.reddit.com/r/todoist/comments/cykokc/i_made_two_tools_to_pick_random_todoist_tasks_my/

**Comment by mdbraber** [comment]
Try something like this: 

```
tasks = getTasks();
setCursor(tasks[Math.floor(Math.random()*tasks.length)],'scroll');
openTaskView();
```

**Comment by antois** [comment]
@mdbraber Thanks for the suggestion. I tried wrapping it up as a bookmarklet and it sadly did not work. Do you think I could use it another way somehow?

**Comment by mgsloan** [comment]
Maarten's code is using functions that are only defined inside todoist
shortcuts.  It avoids putting identifiers in the window object, out of
politeness (and potential accidental shadowing of Todoist's use of the
window object).  So, this would need to be code in a new shortcut handler.
There's some documentation of how to use a locally modified version of
todoist shortcuts:
https://github.com/mgsloan/todoist-shortcuts#how-to-customize-keyboard-shortcuts

Glad to see interest in enhancements!  I am busy right now but hoping to
take a closer look at the recent issue tracker activity in the next few days

**Comment by mgsloan** [comment]
Added in version 139!  Shortcut is `ctrl+?` (aka `ctrl+shift+/`)

**Comment by antois** [comment]
Just tested, works great, thank you for the awesome addition!
