### ISSUE TITLE
Bug: blurSchedulerInput timeout too low in Safari

### ISSUE THREAD

**Issue by mdbraber** [mgsloan/todoist-shortcuts#191]
The `blurSchedulerInput()` function uses a timeout of 0ms breaking it in Safari. Setting the timeout to 100ms fixes this.

**Comment by mdbraber** [comment]
To prevent the blue "Focus" outline to appear on task items in Safari I also included the following CSS code:

```
    // Fix outline appearing on focused items in Safari
    '*:focus',
    '{',
    '  outline: none;',
    '}',
```

**Comment by mgsloan** [comment]
I've written a fix for the blurSchedulerInput issue, will be included in version 139.  I don't want to set it to 100ms because that allows an interval of time where keystrokes will modify the scheduler text.  So instead it retries 20 times with 10ms intervals between, initial pause is 0ms to schedule the async task asap.

I don't follow why that CSS is helpful on safari?  A little hesitant to add CSS for every `:focused` dom element, seems maybe better to make it more specific.

**Comment by mdbraber** [comment]
Thanks for fixing. The CSS should be a separate thing so closing for now.

**Comment by mdbraber** [comment]
I'm reopening this (as I'm returning to Todoist). In Safari / WebKit a small delay is still needed. Could we set a default to 20ms on this line? https://github.com/mgsloan/todoist-shortcuts/blob/master/src/todoist-shortcuts.js#L2723

**Comment by mgsloan** [comment]
It should persistently retry 20 times.  Changing delay there would just add lag when things work faster.  I've increased the retry limit to 50 with 20ms between for a total of 1 second.

**Comment by mdbraber** [comment]
According to all logic it should, but somehow there's a Safari bug that prevents is from working as it should. Increasing the retry limit doesn't make a change, it's really the initial `setTimeout` call. It's probably some weird timing issue which I can't seem to debug, because e.g. manually calling `document.getElementsByClassName('scheduler')[0].getElementsByTagName('input')[0].blur();` in the console works everytime as it should.

Would it be possible to create an IS_SAFARI check?

``
  const IS_SAFARI =
      /Safari/.test(navigator.userAgent) && /Apple/.test(navigator.vendor);
```

And updating the function to:

```
  function blurSchedulerInput() {
    enterDeferLastBinding();
    if (IS_SAFARI) {
       setTimeout(() => blurSchedulerInputImpl(50), 20);
    } else {
       setTimeout(() => blurSchedulerInputImpl(50), 0);
    }
  }
```

I know it's not ideal but seems to be a middleground to preventing adding delays for those who experience no bugs

**Comment by mgsloan** [comment]
Ahh, thanks for the info!  I've implemented a different solution, released in version 171: only stop trying to blur the input if it's found to be focused.  I hope that fixed it?

**Comment by mdbraber** [comment]
Unfortunately the problem remains. I already tried working with document.activeElement (sorry, should have mentioned) but weirdly enought the element *is* active, but the `blur()` just doesn't register. I'll try to figure out if I can find another workaround, but setting the initial `setTimeout` to 20ms still works weird enough.
