### ISSUE TITLE
Navigate through projects

### ISSUE THREAD

**Issue by mdbraber** [mgsloan/todoist-shortcuts#196]
I can navigate through top sections / favorites, but I'd really like to be able to navigate to next / prev project (based on the sidebar). It would be great if we could something like nextProject / prevProject based on the open projects. Seems like this would be easiest by creating something similar to the top sections navigation?

**Comment by mgsloan** [comment]
I've added `nextNavItem` / `prevNavItem` functions, but not sure what keys
to bind them to.

Maybe it's time to consider adding options to todoist-shortcuts!

**Comment by mdbraber** [comment]
Awesome - thanks Michael! Closing this issue.
