### ISSUE TITLE
Feature request: key for opening time prompt when in scheduling view

### ISSUE THREAD

**Issue by masonc15** [mgsloan/todoist-shortcuts#198]
Hello,

This extension is incredible.  As somebody who timeboxes with Todoist pretty aggressively, it would be very helpful if there was a shortcut to open the specific time entry window when in the scheduling view.  I'm referring to this: https://i.imgur.com/tw8bDCv.png

I know you can enter a specific time as part of the text scheduling but a lot of times, Todoist ignores this unless you manually edit the time with the prompt shown above.  Thank you!

**Comment by mgsloan** [comment]
Good idea!  I wasn't aware of that dialog.  I've added the shortcut `alt+t` to access it (also works directly from an item)

**Comment by masonc15** [comment]
Perfect, thanks so much!  I'll test it out when the extension is updated and confirm here.
