### ISSUE TITLE
Tasks within sections sometimes don't show

### ISSUE THREAD

**Issue by coleberhorst** [mgsloan/todoist-shortcuts#199]
This extension is amazing! I did notice that when I look into projects with sections, those projects don't show the tasks that are under sections. The tasks in question were repeating.

**Comment by mgsloan** [comment]
Hi!  I'm glad you like the extension!

That sounds like a Todoist issue to me.  Todoist-shortcuts mostly tries to
stay ouf changing what is displayed.  Does it happen when the extension is
disabled?

**Comment by coleberhorst** [comment]
Yes you were right! I was able to get it happen when the extension was disabled. Thanks for your fast response and awesome extension! I will submit a bug to todoist.
