### ISSUE TITLE
Actions working depends on language

### ISSUE THREAD

**Issue by mmazur** [mgsloan/todoist-shortcuts#2]
Todoist UI language: en – 'm' works correctly.
Todoist UI language: pl – 'm' does nothing.

**Comment by mgsloan** [comment]
Yes, currently it needs to find buttons by searching for the english text.  This is a known issue - https://github.com/mgsloan/todoist-shortcuts/blob/master/development.md#changes-to-todoist-that-would-be-very-helpful - I will email todoist folks about this soon.

**Comment by mmazur** [comment]
Riight, just before you typed this, I dug into the code a bit, noticed why it doesn't work and pinged @amix that I'm sad my language isn't supported. Guess this one stays open until todoist decides to fix this on the backend.

**Comment by mgsloan** [comment]
Yes, there are a couple alternatives:

1. Assume the ordering of clickable elements and use indexes to click.  This seems risky particularly when changes are made to todoist.

2. Hardcode the expected text for all supported languages.  This seems like way too much work.

So I think the best option is if todoist can add different classes for each different button.  I hope this wouldn't be too much work, should be a quick refactoring, maybe an hour or two of work.

**Comment by mgsloan** [comment]
Note that every string that gets matched on has been pulled out into constants - https://github.com/mgsloan/todoist-shortcuts/blob/a3848af/src/todoist-shortcuts.js#L102 - so the minimal thing here would be for todoist to add classes for at least the buttons that have this text.  Ideally classes would be added to everything, though, as otherwise this problem will re-occur as more of todoist gets wrapped.

**Comment by amix** [comment]
Please enable beta (From Settings => General) and you should have classes on menu items.

Do you need any other classes?

**Comment by mmazur** [comment]
Awesome, I'll test it all out in the evening (CET) with the polish ui!

**Comment by mmazur** [comment]
@amix classes for all the single task operations are now in place. However when multiple tasks are selected, the upper menu items still can only be found by text matching.

Please note: Schedule/Move to project/Priority/More… buttons need their own classes, as well as all the menu items under "More…", since Archive and Delete operations are currently supported for multiple tasks at once.

And while you're at it, maybe someone could replace the the three dots in "More..." with the actual unicode ellipsis character '…'? :)

**Comment by mgsloan** [comment]
@mmazur Looks like you've looked into this in depth!  Do you feel like making the change and opening a PR for it?  Would be much appreciated :)

**Comment by amix** [comment]
@mgsloan @mmazur 
In the upcoming beta the upper menu items will have classes (also the "More…" menu) 👍 👍
