### ISSUE TITLE
Opening specific task id without reloading?

### ISSUE THREAD

**Issue by mdbraber** [mgsloan/todoist-shortcuts#200]
Is there a javascript function that allows for loading a specific task without the app reloading? E.g. when I go to https://todoist.com/showTask?id=xxx it will load the task by reloading and showing the task. I'm looking for a way to load a task by id when I've already loaded the page. E.g. when navigating to a "task in project" (shift-G) it doesn't reload. I've tried if manipulating window.location.href would help, but unfortunately to no avail. Any ideas?

**Comment by mgsloan** [comment]
If the task is on the screen then it can be located by ID and then do
something similar to `openTaskView`.

I played a bit with the history API
https://developer.mozilla.org/en-US/docs/Web/API/Window/popstate_event and
found that the following sequence works:

```
history.pushState(null, '', URL);
history.back();
history.forward();
```

I imagine there might be a better way to trigger the popState event than
the back + forward, but hey, it seems to work.

**Comment by mdbraber** [comment]
I've written a Todoist Mac wrapper that responds to todoist:// queries which means the ID comes from an external sources and is fed to the WKWebView. I'm not sure how `openTaskView` is supposed to work in this case? Looking at the code it's supposing an element it can click, which is what I don't have and can't yet wrap my head around :-)

I've tried the popState API, but it doesn't seem to work on Safari?

**Comment by mgsloan** [comment]
Looks like Safari does support the pushState api, but it's possible it
might behave differently - perhaps try other sequences like forward / back
/ forward after the pushState.

**Comment by mdbraber** [comment]
Not sure why, but your suggestion works indeed in Firefox, but to get it to work in Safari I had to use this hack (which does exactly what I was looking for). Thanks!

```
history.pushState(null, '', URL);
history.pushState(null, '', URL);
history.back();
```
