### ISSUE TITLE
Feature request: Copy multiple task titles/urls

### ISSUE THREAD

**Issue by masonc15** [mgsloan/todoist-shortcuts#201]
Hello,

Once again, loving the extension!  Beyond Todoist, I also work in a text file a lot of the time and being able to copy task titles is very helpful to me.  I often have maybe about 10 tasks in a current project I'm working on and usually want to copy all of those tasks.  The current copying shortcuts are great but they don't seem to work with selections of tasks, only for the one task currently "selected" by the cursor.  I'm not sure the complexity of this change but it would be a great addition to my workflow!

FYI:  I am currently using [this extension](https://chrome.google.com/webstore/detail/copy-todoist-tasks/cifleikfldjohjpfkjpngjldplllcnol) for some of my copying needs since it's very straight-forward and allows bulk copying.  However, I think it makes sense to be included in this extension as well and I thought I would mention it since I'm invested in the long-term viability of this extension.  Thanks!

**Comment by mgsloan** [comment]
Good idea!  Pretty straightforward to implement, so added it, included in version 143.  Enjoy!

**Comment by masonc15** [comment]
Piggybacking off of this closed issue since somewhat related:

Is there a way to disable the "Message from todoist-shortcuts" popup upon copying tasks?  Is this from the extension or is it part of Todoist itself? I find it a bit intrusive.  This is a very niche issue so no problem at all if you don't think it's worth addressing.  Thanks!
