### ISSUE TITLE
Toggle todoist-shortcuts message pop-up

### ISSUE THREAD

**Issue by masonc15** [mgsloan/todoist-shortcuts#202]
Is there a way to disable the "Message from todoist-shortcuts" popup upon copying tasks? Is this from the extension or is it part of Todoist itself? I find it a bit intrusive. This is a very niche issue so no problem at all if you don't think it's worth addressing. Thanks!

**Comment by mgsloan** [comment]
This can be disabled in the code (see the instructions in the readme for local modifications).  Currently todoist-shortcuts does not have any options (customizing keyboard shortcuts is tracked by #99)

The reason for the pop-up is that nearly all of the shortcuts have a visual indication that something happened.  Modifying the clipboard does not, and users might be surprised to find their clipboard modified after using one of these non-standard (not ctrl-c / ctrl-x) bindings for modifying the clipboard.

**Comment by mgsloan** [comment]
Closing as wontfix
