### ISSUE TITLE
Shortcuts to set priority in list view not working

### ISSUE THREAD

**Issue by error9900** [mgsloan/todoist-shortcuts#207]
Extension: v144.
Todoist Web: v2055
Browser: Google Chrome

Seems maybe a recent update to Todoist broke using the number keys to set priority level in the list view?
It still works fine in the task view.

EDIT: They work if I disable the Todoist Shortcuts extension and just use built-in Todoist keyboard shortcuts, which I think rules out another extension or Chrome interfering?

EDIT: This might help with troubleshooting: If I select multiple tasks, then hit `1`, it opens the bulk Priority change drop-down at the top of the window (but doesn't actually change the Priority level).

**Comment by mgsloan** [comment]
Thanks for reporting!  Fixed it in version 145.

**Comment by mdbraber** [comment]
With extension v149 on Firefox 101 (macOS Monterey) the priority shortcuts (`1`, `2`, `3`, `4`) set the priority, but also open the edit mode (they don't when disabling the Todoist Shortcuts extension). This prevents from quickly setting priorities like was possible previously

**Comment by Fricounet** [comment]
For information, I have the same issue on Chrome version `102.0.5005.61`  (MacOS Monterey). And @mdbraber fix solves the issue for me too. For now, I have not found any unwanted side effect with the fix.

**Comment by mgsloan** [comment]
Thanks for the fix info!  Will be included in version 150 which will be released soon.
