### ISSUE TITLE
Search autocomplete without execution // query persistence post-execution

### ISSUE THREAD

**Issue by jakelfreeman** [mgsloan/todoist-shortcuts#208]
2 low priority features, but ones I suspect are fairly simple to implement and pretty valuable (at least for me, maybe I'm alone on this)... 

1) When starting a search in the top bar, [TAB] should autocomplete the focused match **_without_** executing the search to facilitate construction of compound queries on the fly
2) Searches should remain in the search bar to facilitate quickly & easy additions to an existing search rather than having to copy/paste or type from scratch

**Comment by mgsloan** [comment]
Makes sense!  However, this is a bit different than what todoist-shortcuts typically does - it mostly just adds keyboard shortcuts which trigger synthetic mouse interactions.

These changes are more like modifications of how Todoist itself behaves, and so it would be the extension working around / modifying existing Todoist behavior.  This is certainly possible, but I'm not keen on getting into modifying Todoist behavior.

I suggest contacting Todoist support with this suggestion!
