### ISSUE TITLE
Shortcuts for subtasks not working

### ISSUE THREAD

**Issue by antois** [mgsloan/todoist-shortcuts#209]
Hi there, thanks for the great extension once again.

I've noticed that after the recent task view UI upgrade the subtask shortcuts are not working. Steps to reproduce:

1. Open any task
2. Try to manipulate subtasks with any shortcuts: q, a, A are not working, as well as 1-4, etc...

Do you think it could be possible to fix this, at least for adding and deleting subtasks? That would be awesome!

**Comment by mgsloan** [comment]
Version 149 fixes most task view shortcuts (may only work for english version of todoist..)

I do not plan to add bindings for subtasks other than adding them (see #188 and #94)

**Comment by antois** [comment]
Hi @mgsloan , thanks for a rapid follow-up on this. 

I've updated to v149 and tested sub-tasks once again: sadly, they still don't work. For example, pressing "a" / "A" / "q" on English version of Todoist new task view just opens labels for a given task, instead of creating new subtasks. Is that intended behaviour and was not covered by the fix?

**Comment by antois** [comment]
PS: pressing "e" or "#" in the task view opens "More actions" menu, instead of deleting a selected sub-task.

**Comment by mgsloan** [comment]
Thanks for following up on this @antois I've fixed the issue with adding tasks in task view when there are already subtasks

**Comment by antois** [comment]
@mgsloan thank you for the fix and for your work on the extension overall, it really helps
