### ISSUE TITLE
Add task shows "quick add" when grouping by priority

### ISSUE THREAD

**Issue by mdbraber** [mgsloan/todoist-shortcuts#211]
With Todoist v2145 on macOS Monterey (Firefox 101):  when grouping by priority, adding a task pressing `a` pops up the quick add window, rather than the inline add task view. I would expect it to work as in the regular Todoist (without extension) where it would open the inline add task view per section.

**Comment by mgsloan** [comment]
Thanks for reporting!  Fixed in version 150

**Comment by mdbraber** [comment]
Sorry for re-opening this, but the fix doesn't seem to work. When opening a project in viewMode `project` and grouping by priority it still opens up quick add. It seems that after calling `clickInlineAddTask` it doesn't get the right section from `getSection` and therefore uses the `document` element to find `plus_add_button` which returns multiple elements, instead of a unique one. Therefore it falls back to quick add. I can sort of follow what's going wrong, but presume you're the better judge of what should be the fix @mgsloan :-)

**Comment by mdbraber** [comment]
This update seems to be a bit more complicated than anticipated, maybe, but I think we could do this:

It seems the function call on https://github.com/mgsloan/todoist-shortcuts/commit/b872df341d4e2cf753529c7ad941baf372e7184f#diff-cf9068b3f646efbdc31761df1ec3f305a90efa486d9de313ec4fbbfe5c4fa0c2R2797 - is missing the `all` parameter and a function call. Should that be something like (`button => { return button; }`) ?

The `addAboveOrBelowTask` call should maybe call `addToSectionContaining(task)` on https://github.com/mgsloan/todoist-shortcuts/blob/0ad316b378db3123daadf457a73813a85d4f3099/src/todoist-shortcuts.js#L2762 (which contains the quick add fallback too)

**Comment by mdbraber** [comment]
@mgsloan can we reopen this issue? See suggested fixed above.

**Comment by mgsloan** [comment]
@mdbraber Oops, sorry about the long delay on this.  Fixed in version 152!
