### ISSUE TITLE
extension breaks the new task view

### ISSUE THREAD

**Issue by brettmiller** [mgsloan/todoist-shortcuts#213]
Todoist introduced a "new task view" in [Web version 2083](https://todoist.com/help/articles/whats-new#introducing-new-task-view-may-24-%E2%9C%A8). With the todoist-shortcuts extension enable the new task view doesn't work and is the old style. With the extension disabled the new task view works as expected.

**Comment by mgsloan** [comment]
Hey, what version of todoist-shortcuts are you on? This has been discussed on #204 

I did just notice that the scheduling keybinding was broken, but that is now fixed in version 151

**Comment by brettmiller** [comment]
I'm on 152. The extension works, but it ends up with the old task view instead of the new view. 

This is what I see after hitting Enter with a task selected

Without the extension enabled:
![todoist_task_without_shortcuts_extension](https://user-images.githubusercontent.com/1895215/174387411-d68d7c62-0ae3-440d-a3bf-2dd117f004a0.png)

With the extension enabled:
![todoist_with_shortcuts_extension](https://user-images.githubusercontent.com/1895215/174387465-f660aaa4-acd0-4234-82ab-186a6b362acc.png)

**Comment by mgsloan** [comment]
Oh, yeah, that's just how todoist shortcut's keybindings work.  "i" is the
key to open task view.  Task view got a funny shortcut because
todoist-shortcuts predates the addition of the task view.

Happily, there are many similarities because Todoist took inspiration from
this extension.  However, I cannot change the extension's behaviors without
negatively impacting the muscle memory of the ~2000 users (and my own
muscle memory)

I know, this isn't great for people who start with Todoist native
shortcuts, maybe I will finally cave and add some options / configurability
to this extension...

**Comment by brettmiller** [comment]
Ah, that makes sense. I've been using this extension pretty much since I started using Todoist, but I've always just used 'Enter' to modify a selected task and when Todoist announced changes to the selected task view and I wasn't seeing them I turned off the extension to see if that was why and it was. I can try to modify my habits to use 'i' if I want see the new task view. 

I have noticed something that does seem to be an actual bug. If you hit 'enter' to edit a task and then 'esc' to close it, the focus is taken away from the task, but the task isn't properly closed (as it would be if clicking the 'cancel' button). You also can't select the task again after it looses focus unless you either tap it's 'cancel' button or select another task with 'enter' (then that task goes into the same weird state). After hitting 'esc' and the task loosing focus it seems to put focus on the previous last in the list, but the highlight to the left of the task to show it as selected isn't there. If this would be better in a new issue let me know and I can open one and then this one can be closed.

**Comment by mgsloan** [comment]
> If you hit 'enter' to edit a task and then 'esc' to close it, the focus is taken away from the task, but the task isn't properly closed

Hmm, curiously I don't see this bug!  For me escape closes the task editor.  Feel free to open a bug about it.

> You also can't select the task again after it looses focus unless you either tap it's 'cancel' button or select another task with 'enter' (then that task goes into the same weird state). After hitting 'esc' and the task loosing focus it seems to put focus on the previous last in the list, but the highlight to the left of the task to show it as selected isn't there.

Ah, good catch!  Fixed this in version 153.
