### ISSUE TITLE
Option to turn off mouse changing task focus

### ISSUE THREAD

**Issue by ravivmg** [mgsloan/todoist-shortcuts#214]
I love the ability to navigate with the keyboard using vim style commands. As a feature request, I wish that I could turn off having the task that is focused change when I move the mouse. I would rather that the focused task only responded to keyboard inputs and not the mouse movement.

Could there be an option in the extension options to turn off the usage of the mouse for task focus?

**Comment by mgsloan** [comment]
Good point!  Mouse usage for this was actually specifically requested by Todoist folks.  I also prefer to have it disabled, but it didn't bug me all that much.

So far I'd resisted the complexity of adding an options page, but have now added one, so future addition of options should be much easier.
