### ISSUE TITLE
Go to subtasks 'i' + 's' does not work on Mac/Chrome

### ISSUE THREAD

**Issue by ravivmg** [mgsloan/todoist-shortcuts#215]
On Mac Chrome Version 102.0.5005.115 (Official Build) (x86_64) + version 152. I can hit 'i' to go into the task view, but hitting 's' does not bring the focus to the subtasks.

**Comment by mgsloan** [comment]
Hey!  Sorry about that, the shortcuts sheet hadn't been updated to reflect recent changes.  Since Todoist no longer has different sections for these, there is no longer an `s` shortcut in the task view.

Subtask management from the task view is not currently planned - see discussion in #210
