### ISSUE TITLE
Task view: esc button closes task view instead of closing active sub-task or comments window

### ISSUE THREAD

**Issue by antois** [mgsloan/todoist-shortcuts#217]
Hi there, once again thanks for the extension. I've noticed a bug with hitting esc in task view. Steps to reproduce:

1. Open task view
2. Click to add a new sub-task or input text in comments section
3. Hit esc to get back to task view from the activated field

→ instead of closing the activated field, the task view itself is closed upon hitting esc. This does not happen if this extension is disabled.

**Comment by mgsloan** [comment]
Ah, good catch!  Fixed in version 159

**Comment by mgsloan** [comment]
Unfortunately having some issues with getting things updated in the chrome webstore, as I'd uploaded some prior zips with missing files, which were rightfully rejected.  Version 157 is still pending review, so I can't upload 159 yet.  So for now stuck on version 152 in chrome webstore, hopefully will be resolved soon.
