### ISSUE TITLE
Did Todoist v2238 broke this extension?

### ISSUE THREAD

**Issue by llinfeng** [mgsloan/todoist-shortcuts#218]
Starting this morning (2022-07-05), when I reload a Chrome tab for Todoist.com, this extension stopped to load. I think it was working fine with v2237.

**Comment by mgsloan** [comment]
Unfortunately version 157 of todoist-shortcuts is broken by my mistake.  I realized this mistake moments after uploading, but unfortunately chrome web store is sometimes taking days to review new uploads, and now does not take updates to uploads after the review process is initiated (which seems really really inefficient to me..).  Hopefully it's related to holidays or something, so the update to 159 will go faster.

Fixed in version 158 via https://github.com/mgsloan/todoist-shortcuts/commit/6d9f457798976c10077655b5818d2b594c6f3f85

**Comment by llinfeng** [comment]
Thanks a lot for your very prompt response and quick fix. Upon reloading the todoist.com page, the extension is loaded again! 

I assume Chrome handles extension updates automatically. Now I see Version 159 via this address: `chrome://extensions/?id=dehmghpdcahlffompjagejmgbcfahndp`.

----

Thanks again! It was not fun to learn the "native" keyboard shortcuts - one funny thing is how `<c-e>` is chosen as the keyboard shortcut for editing a task - it coincides with the `e` key for marking a task as finished, and would also conflict with Chrome's search shortcut easily (on Windows machines at least).

**Comment by mgsloan** [comment]
Welcome!  Yes, happily this time the review for version 159 went through quickly!

> Thanks again! It was not fun to learn the "native" keyboard shortcuts - one funny thing is how <c-e> is chosen as the keyboard shortcut for editing a task - it coincides with the e key for marking a task as finished, and would also conflict with Chrome's search shortcut easily (on Windows machines at least).

Yeah!  I'm glad that Todoist took a lot of inspiration from todoist-shortcuts, but of course I'm biased in thinking that sticking closer to the decisions in todoist-shortcuts would have been good.

One thing I've considered is that some users now may be coming from using Todoist's native shortcuts, which means it would probably be good to do things like:

1. Clearly document the advantages / additional shortcuts
2. Document the differences
3. Maybe even have a mode which matches Todoist's choices of shortcuts (maybe along with the ability to fully customize shortcuts #99)

In the long run it may also make sense for this extension to start being a thinner layer atop Todoist's native shortcuts.

However, all of these things take time and effort and for me this project is currently in maintenance mode. :thinking:
