### ISSUE TITLE
Task view: pressing "c" to jump to comments section does not work

### ISSUE THREAD

**Issue by anton2020** [mgsloan/todoist-shortcuts#219]
Hey, thanks again for the extension. I've noticed that while in the task view, pressing "c" to jump to comments section does not work, although my understanding is that it is covered by this extension and the original version. Steps to reproduce:

1. Open any task in task view
2. Press "c" - comments section is not activated

**Comment by mgsloan** [comment]
Good point!  Added this in version 163
