### ISSUE TITLE
Possible to shortcut key in Gmail to add website as task

### ISSUE THREAD

**Issue by rujschafer** [mgsloan/todoist-shortcuts#220]
Just stumbled on this extension which I will be installing momentarily because it looks great.

I am looking to shortcut key the add website to task in Gmail.

There is a Todoist extension which gives you a clickable link but that is tedious and I am much faster typing than with the mouse. 

Appreciate the consideration!

**Comment by mgsloan** [comment]
Hey, it's a good idea!  Considered this some in #61 but decided it belongs in a separate extension which I do not plan to write.

I encourage someone to do so, though!
