### ISSUE TITLE
After changing priority with 1/2/3/4 key, the affected task stays "in focus" => not possible to process a list

### ISSUE THREAD

**Issue by andreasfmwolf** [mgsloan/todoist-shortcuts#221]
After changing priority with 1/2/3/4 key, the affected task stays "in focus".
When I use the arrow keys afterwards, the task up/down to the new position of the affected task is selected.

This is an issue, as it makes it very hard to process a list of tasks, as I always need to keep pressing the arrow keys many many times to get back to the place in the list, which I was previously at when sorting through the list.

**Comment by andreasfmwolf** [comment]
Thanks so much for the speedy reply, Michael! 😊
Just want to add that I love your extension - makes the great Todoist even so much better!! Thanks a million!! 🥰

I'm slightly confused, as I'm almost 100% sure that the cursor behaviour was staying in position in the previous built I've used (1.36, I believe)?!

Any chance that I can switch cursor behaviour by editing a parameter in the "todoist-shortcuts.js" file? 🙏✨

**Comment by mgsloan** [comment]
I imagine the behavior change was https://github.com/mgsloan/todoist-shortcuts/commit/b6fd44ba4f6073d3bb7fe7dcee70ac80ae7f225d .

I've worked some on this but haven't managed to add an option for what you want here.  Todoist-shortcuts uses the task id / indent / section to store the cursor, and so it is rather tricky to have the cursor not move with priority change.

I have however added an option that enables / disables the cursor following across section changes, and implemented some fixes of that.  So, as a workaround for now, with the default setting of not following across section changes you should be able to:

* Group by priority
* Change task priorities without this moving the cursor with the task

**Comment by andreasfmwolf** [comment]
Hi Michael
Wow, I'm just so super grateful for what you're doing here!
Your workaround works perfectly for me... so happy I can use Todoist again with full keyboard control the way I'm used to!! 🤩 Thank you, thank you, thank you!!! 💛

**Comment by mgsloan** [comment]
@andreasfmwolf You're welcome!  So glad this approach is working well for you :grinning:
