### ISSUE TITLE
foreign keyboard layout

### ISSUE THREAD

**Issue by davidszp** [mgsloan/todoist-shortcuts#222]
Using my standard German keyboard layout, I am not able to move cursor focus to the multi-select bar using , (comma) after selecting multiple tasks. I have tried this in Chrome and Firefox with the same result.

Switching off the todoist-shortcuts extension restores functionality.

Then I switched my keyboard layout to US, using Windows. To my surprise, still the extension would not feed through the comma key. Restarted browsers, no dice.  Is this another issue related to JS mousetrap? If so, shouldn't it work using a US layout?

**Comment by mgsloan** [comment]
Yes this is probably the same as #180 .  Unfortunately it's hard for me to fix because I do not have a foreign keyboard layout.  Contributions welcome!  Indeed maybe fixing upstream in mousetrap would be the way to go
