### ISSUE TITLE
Indent multiple tasks at once

### ISSUE THREAD

**Issue by ravivmg** [mgsloan/todoist-shortcuts#224]
If I select a number of tasks at once using "x" and then try to indent using "shift-right arrow" only the first task indents.

Is that a todoist issue or is there a way that todoist-shortcuts could indent all of the selected tasks at once?

**Comment by mgsloan** [comment]
Hey, glad you're appreciating todoist-shortcuts.

It's conceivably possible, but since it is not built in to todoist it would be fairly complex and error-prone to implement.
