### ISSUE TITLE
Upstream Todoist issue: Can't undo archiving multiple tasks at once

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#23]
Repro:

1. Add a couple items, and select them
2. Either use `e` to archive, or use the mouse ui, via shift+click and `More... -> Archive`
3. Press undo.

Expected:

* Box pops up saying `2 items completed`
* Pressing undo brings back both items

Actual:

* Box pops up saying `1 item completed`
* Pressing undo only brings back one

A somewhat related issue is that you can't undo a deletion.

**Comment by mgsloan** [comment]
Somewhat related is that you cannot undo task deletion.

**Comment by amix** [comment]
Added a task to take a look at this. Thanks for the report @mgsloan 👍

**Comment by mgsloan** [comment]
Closing this issue as part of a general issue tracker cleanup
