### ISSUE TITLE
Task selection no longer responds to cursor position

### ISSUE THREAD

**Issue by jakelfreeman** [mgsloan/todoist-shortcuts#230]
Up until recently when hovering over a task with the cursor, it would become the active task (slim blue bar would appear along the left hand side). Seems to be broken in v2719. I suspect this is a common issue but if not, let me know and I can copy/paste in the error messages from the dev console.

**Comment by mgsloan** [comment]
Hmm, curious!  It seems to work for me.  Did you mean to close this issue?

One thing to note is that I added a setting that controls this behavior

![image](https://user-images.githubusercontent.com/22570/202928571-a89e4dea-f1b2-47d1-ab51-bb65dcd1dcb4.png)

So worth checking that too (this is accessed by right clicking the extension icon and clicking "Options", or similar from chrome://extensions)

**Comment by jakelfreeman** [comment]
Yes, I meant to close it--I think it was an issue with an old Chrome version. Problem went away as soon as I updated my browser. Apologies for the false alarm!

**Comment by mgsloan** [comment]
No worries, glad it's working!
