### ISSUE TITLE
Task Pane Steals Focus from Search Bar

### ISSUE THREAD

**Issue by jakelfreeman** [mgsloan/todoist-shortcuts#231]
I'm experiencing an issue after typing in the search box--when I press enter to execute the search, the app goes into edit mode on the active task in the task pane rather than executing the search. I've confirmed that the issue is with this extension, not the app itself or another extension. Running v2852 on Chrome.

**Comment by jakelfreeman** [comment]
Can anyone else confirm whether they're experiencing this issue? Still happening in v2882(beta) for me

**Comment by mgsloan** [comment]
Initially I couldn't reproduce this issue, but I think I may have found a
way!  If I do a very quick enter keystroke like usual nothing happens.
However, if I do a longer hold before releasing, it does trigger
todoist-shortcut's binding for "enter", to edit the task focused.  I can't
try to fix this today, but will try to soonish

**Comment by jakelfreeman** [comment]
Thank you! I'm unclear as to why duration of keypress would make a difference, but regardless, very much appreciate your help & attention.

**Comment by mgsloan** [comment]
Oh, just noticed this issue specifies "task pane".  If the problem was invoking todoist-shortcuts' handler, then it would be opening the inline task editor instead of the modal dialog.

So, if it is opening the task pane then that means somehow Todoist's native `enter` shortcut is getting triggered.  Clearly this is due to some interaction with todoist-shortcuts if it goes away when the extension is disabled, unfortunately the code for intervening on keyboard handling is pretty convoluted

**Comment by jakelfreeman** [comment]
What does this mean from a solution standpoint? I'm very surprised that only myself and one other user seem to be having a problem because the bug inhibits a pretty critical piece of functionality (effectively I'm unable to execute a search without use of the mouse). See the attached video which shows what happens when a search is typed and I try to navigate through the auto-populate items with my arrow keys (winds up navigating through the tasks instead) and then try to execute the search with the enter key (enters edit mode with the highlighted text instead). Any ideas how I can go about fixing this?

https://user-images.githubusercontent.com/3990322/212556154-22a53f45-b6b8-492a-a3f4-13aab7e59ae0.mov

**Comment by mgsloan** [comment]
Ahh, thank you for the video, that was helpful!  I think the missing part of the repro steps was to select an item from the dropdown.  Once I did that I also see the bug

Happily, the fix (in version 172) also means that arrow keys will now be able to navigate the list of search results whereas before they did not.
