### ISSUE TITLE
Priority Shortcuts (1,2,3,4) stopped working on Chrome extension (Windows 10)

### ISSUE THREAD

**Issue by frankydee** [mgsloan/todoist-shortcuts#235]
Hi!
I am using Todoist Shortcuts v. 170 on the latest Chrome Version 109.0.5414.75 (Official Build) (64-bit) on a Windows 10 PC and shortcuts 1,2,3,4 to assign priorities when browsing issues in list view no longer work. 
Thanks!

**Comment by frankydee** [comment]
Ooops... I updated chrome and it's fixed.  Sorry for the false alarm! 😏

**Comment by mgsloan** [comment]
No worries!  Probably just the extension not being updated yet, this was fixed yesterday in #233
