### ISSUE TITLE
Get followLink to find links in task_content OR task_description

### ISSUE THREAD

**Issue by mdbraber** [mgsloan/todoist-shortcuts#236]
I'm trying to get `followLink` to find a link either in the `task_content` (title) or `task_description` - but don't know what the best code would be. Any suggestions?

**Comment by mdbraber** [comment]
Well - maybe it's simpler than I thought: could we change `task_content` in https://github.com/mgsloan/todoist-shortcuts/blob/master/src/todoist-shortcuts.js#L462 to `task_list_item__content` (which is the div including `task_content` and `task_description`). Would that break anything else @mgsloan ?

**Comment by mgsloan** [comment]
Good idea!  I didn't notice this since I never use descriptions (though maybe I should!).  Included in version 173
