### ISSUE TITLE
Still seeing priority changing issue with experimental feature on

### ISSUE THREAD

**Issue by erauner12** [mgsloan/todoist-shortcuts#238]
Hi 🙂  
  
I've gone ahead and turned experimental features back off. After testing this change #233, I am still seeing the issue? Anyone else?

test:

to be sure I was testing correctly I completely uninstalled the shortcut. Restarted chrome. installed the shortcut again. refresh todoist page. 

result: Still cannot change priority via shortcut buttons `1` , `2`, `3`, and `4` 🙁

Sorry for the trouble if this is a false alarm, but I am not sure what I could be doing wrong if this was fixed?

**Comment by mdbraber** [comment]
I've got experimental features turned on and it's working for me. Are you sure you have the latest version running?

**Comment by erauner12** [comment]
Yeah I'm not sure? I'm on `v2988 (beta)`, is that what you are on?

**Comment by erauner12** [comment]
strangely, what I have noticed as well when I turn on experimental features is that my up and down arrow navigation breaks as well? Not sure if it related or what.

**Comment by mdbraber** [comment]
Mostly interesting is what version of the shortcut is running - can you check if it's indeed v172?

**Comment by erauner12** [comment]
I confirmed at the end of this video that the plugin is indeed on `v172` (plugin) and `v2997` (todoist web)on my mac (which is strange because it was on `v2998` before so they must have rolled it back)  
  
I also found some interesting behavior that I did not recognize before (actually just recognized it as I was creating the video)  
  
It seems that the priority is assigned in some cases, but not others (when on experimental) (00:30 timestamp in the video when I test this).

*   I have a keycastr running to show my input to explain what I mean
*   from what I can tell, if the status is nothing, then it cannot be assigned to anything. But if the status is already assigned to a specific priority, I can in fact change it to something else (even `0`). But then at that point, I cannot change it back to `1`, `2`, `3`, or `4`?

Let me know what you think.

https://www.loom.com/share/98df25ac3ecd412489c4ac2c852e9cc5

**Comment by erauner12** [comment]
I decided to take another loom on just experimental mode to hone specifically on what I believe the problem is:

*   priority cannot be assigned on expirimental mode unless it already exists as either `p1`, `p2`, or `p3`. If `4` is used (effectively removing priority `p4`) priority cannot be assigned to anything else)
    *   whereas when expirimental mode is off, priority can be assigned via todoist-shortcuts regardless of what the existing status is (which can be seen in the former video)

  
[https://www.loom.com/share/9b20466a4c14492f98f1f12cbee687fe](https://www.loom.com/share/9b20466a4c14492f98f1f12cbee687fe)

Sorry if any of this is confusing. Please let me know if I can show better

**Comment by mdbraber** [comment]
I'm on 2998 and it's been working for me for the last few versions. Do you have any output in the JS console that might indicate what might be happening?

**Comment by erauner12** [comment]
Will work on getting this!

**Comment by mgsloan** [comment]
Recently priority changing of a single task broke for me with experimental features on.

I think I know why only some people see the breakage.  When opening the edit, there's a modal popup that says "⚡️ New: Pick your Quick Add options."  Todoist-shortcuts was getting confused as it was finding a popup in order to find the priority selection menu.  However, then it would immediately exit edit mode.  This would all happen so quickly the popup never even gets displayed to the user.

I'm assuming that was the issue, so closing this.
