### ISSUE TITLE
Upstream todoist suggestion: ability to enter text for multi-item reschedule

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#24]
If you select multiple items and press "Schedule", a calendar pops up for rescheduling.  However, since there is no text entry, it does not seem to be possible to set event recurrence for multiple items at a time.  For todoist-shortcuts, it also means I'm considering implementing a complicated system to let you type the numbers of days from the calendar view :O

**Comment by amix** [comment]
We are redoing the scheduler, so I would not recommend changing anything right now :)

**Comment by mgsloan** [comment]
Yep, looks like this is now on https://beta.todoist.com - great stuff!
