### ISSUE TITLE
Bug: Undo not working

### ISSUE THREAD

**Issue by danrthompson** [mgsloan/todoist-shortcuts#243]
I don't know if this is an issue specific to me. I do have a lot of other extensions enabled, and perhaps one is interfering. But undo is currently  not working. I've tried refreshing the page, disabling and re-enabling extensions, etc. I also tried each undo shortcut option separately. As in, I created Test task 1, completed it, then (while the Undo button was still visible), tried `u`. Didn't work, so I did the same process for the other listed options (z and ctrl-z, as well as the additional native Todoist shortcut: cmd-z).

None of them did anything.

I'm on a Macbook Pro, on Chrome (obviously), latest version of each, and using the Todoist web app.

Lmk if there is any additional information I can provide or if you have trouble replicating the issue.

Dan

**Comment by mgsloan** [comment]
This has actually bugged me for a while, but been busy so only just got around to fixing it.  Fix is included in version 178!
