### ISSUE TITLE
Collapse/expand not working?

### ISSUE THREAD

**Issue by basilhalperin** [mgsloan/todoist-shortcuts#244]
Hi, thanks for the amazing add on. For the last week or so, collapsing/expanding with the left/right arrow keys hasn't been working, for me at least. Thought I'd create an issue for this since one doesn't seem to exist (sorry for not attempting to debug myself!).

**Comment by markrhysmitchell** [comment]
I've come here with this same issue! +1

**Comment by mgsloan** [comment]
Fixed!  Included in version 178

Thanks for reporting!
