### ISSUE TITLE
Indent task not working

### ISSUE THREAD

**Issue by GaryFurash** [mgsloan/todoist-shortcuts#249]
Using Edge (latest) on windows

If I turn off todoist shortcuts, I can use ctrl[] to indent / outdent tasks. 

If I turn on the extension, then I can't use ctrl[] to indent OR the extension's indent/outdent (shift-right/h)

**Comment by atkinsmedley** [comment]
I'm seeing this issue in Brave browser as well (also Chromium based).

**Comment by mgsloan** [comment]
I believe this is the same underlying cause as #248 so closing as a duplicate.

Thank you though!  Helpful point that todoist itself has some native shortcuts for this.

**Comment by mmcintyre123** [comment]
@mgsloan I see this as well - the native shortcuts for increasing and decreasing a task's indent work without the extension enabled. Any chance for a fix for that in the extension?  Would also still love to see a fix for #248 / #241.   I just submitted a feature request to todoist to add native keyboard shortcuts for moving tasks up and down.
![image](https://github.com/user-attachments/assets/205249c1-a517-441c-897e-365c8ff18fcf)
