### ISSUE TITLE
A strange problem

### ISSUE THREAD

**Issue by zephyrer** [mgsloan/todoist-shortcuts#25]
Now I met a strange problem: When this extension enabled, original todoist.com hotkeys (a, A, / or f) are all invalid, the hotkeys added by the extension are valid. When disabled the extension, original hotkeys (a, A, / or f) do work!
Then I create a new profile, install this extension only, log into todoist.com. Till this step everything well: all hotkeys, whether origins or extension added, are valid. Disable the extension and re-enable, there are keys added by the extension worked.
Why? How to solve?
PS: todoist.com ver 906
    Firefox 61.0b12
    todoist-shortcuts 11

**Comment by mgsloan** [comment]
Hmm, that's strange indeed!  For me those all of those keypresses work.

I'm guessing `u` for undo also doesn't work? How about `s` for sort by date?

The way those work is by simulating keypresses.  It might work better to pass those particular keypresses through.  I'm thinking it might have something to do with locale settings.

**Comment by zephyrer** [comment]
yes. all originals are invalid when todoist-shortcuts enabled

**Comment by mgsloan** [comment]
While I have not seen this problem myself, I believe that this should be fixed in version 15.  Keypresses that are not handled by todoist-shortcuts now get passed through to Todoist.
