### ISSUE TITLE
Shortcut keys stop displaying after first few items

### ISSUE THREAD

**Issue by paymarkconnex** [mgsloan/todoist-shortcuts#250]
The shortcut hot keys have stopped displaying after the first few items:

![image](https://github.com/mgsloan/todoist-shortcuts/assets/120440843/a98af9cb-d868-4107-a4fe-98f00b6c53f0)

Todoist is pushing so many updates I may have missed when it actually happened, but I'm on v4197. Chrome is 116.0.584.140

**Comment by San88-source** [comment]
I just made an account to say: yes, please fix this!

**Comment by mgsloan** [comment]
Fixed in version 179!  Sorry for the delay, been rather busy with other things.
