### ISSUE TITLE
Default search key broken with new update

### ISSUE THREAD

**Issue by jakelfreeman** [mgsloan/todoist-shortcuts#251]
Pressing "/" no longer opens the search dialogue box in v4234

**Comment by cnxguy** [comment]
Looks like search now opens the new "unified Quick Find" rather than being an input box as it was before. Seems to be a button. I'm not a JS/Web guy but looks like the name may have changed too, quick_find__input to quick_find?

I'll let @mgsloan figure it out.

**Comment by mgsloan** [comment]
Thanks for reporting! Fixed in version 180
