### ISSUE TITLE
Section navigation mode

### ISSUE THREAD

**Issue by basilhalperin** [mgsloan/todoist-shortcuts#259]
Hi, thanks once more for this fantastic add-on.

If I'm not mistaken, then "section navigation mode" hasn't been working for a week or so. I may look into this myself later, but also wanted to leave this report to confirm that it's not an issue on my end. Thanks.

**Comment by mgsloan** [comment]
Guessing you had the new UI enabled?  Recent versions of the extension fix this.  Feel free to reopen if still broken.

**Comment by basilhalperin** [comment]
I'm not sure if I'm on the new UI or not 🤔 (I don't remember enabling anything). I'm on version 185 of the extension, which looks like the latest version (and just tried restarting Firefox) -- I'm still seeing that it doesn't work. (Could I be screwing something up?)

**Comment by mgsloan** [comment]
Ahh, just tested in firefox and looks like the `el.computedStyleMap()` function isn't supported by firefox.

For now version 187 includes a partial fix.  Navigation mode will work, but the sidebar menu won't automatically open if closed

**Comment by basilhalperin** [comment]
(Thank you!!!!!)
