### ISSUE TITLE
Editing selected task while in task view

### ISSUE THREAD

**Issue by flinesse** [mgsloan/todoist-shortcuts#265]
Hi, I've been using this plugin with Todoist running as a PWA, and the experience has been much better compared to running the app natively. One thing I've felt consistent friction over however, is the lack of a keybind to edit the task while in [task view](https://github.com/mgsloan/todoist-shortcuts#task-view). It feels awkward to not be able to edit while having the selected task front and center, needing to resort to hitting \<tab\> multiple times to cycle through DOM elements until I get a hover on the task description box. I feel like a keybind for this would be a sensible and practical addition—helpful when there is a need to edit without distractions, i.e. when writing notes (uncompletable tasks) or tasks with lengthier descriptions. I'd like to see this be possible, perhaps with \<enter\> or \<i\> (currently bound to `taskViewClose`).

I'm curious to hear your thoughts. Thanks again for this wonderful project.

Sidenote: I leverage [(S)uper (D)uper Mode](https://github.com/jasonrudolph/keyboard#super-duper-mode) from jasonrudolph/keyboard to achieve a mouseless textbox editing experience on macOS, which makes this potential feature even more appealing to me. I believe [glacambre/firenvim](https://github.com/glacambre/firenvim) also helps achieve this, but have not tried it personally.

**Comment by mgsloan** [comment]
Forgot to comment here / close.  Great point definitely an omission.  As of version 191 a few weeks ago, enter now edits the task in task view
