### ISSUE TITLE
Project switching / task cursor broken in Firefox

### ISSUE THREAD

**Issue by basilhalperin** [mgsloan/todoist-shortcuts#267]
Amazing add-on as always. 

Am I wrong to see that project switching is not working in Firefox? Same with the task cursor (and the related functions of e.g. changing task priority).

I'm on version 192 in Firefox. (I see it all working fantastically on the latest version in Chrome.) Thank you!

**Comment by danielmaniezo** [comment]
I am also experiencing a lot of issues on Firefox. Completely broken for me.

**Comment by mgsloan** [comment]
Thanks for reporting y'all!  I think it's fixed in version 193
