### ISSUE TITLE
Reschedule no longer works in v5085

### ISSUE THREAD

**Issue by jakelfreeman** [mgsloan/todoist-shortcuts#268]
The dev team at Todoist has done it again... their incessant updating has broken the "t" shortcut to reschedule tasks in v5085. Generates the following message in the console:

todoist-shortcuts: Couldn't find unique descendant matching query button[data-action-hint="multi-select-toolbar-scheduler"] , instead got null

**Comment by champagnealexandre** [comment]
Hey,

I’m just a newb playing with the web inspector but I think I got it working. The `t` shortcut seems to be working fine in the task list so I’m assuming you’re talking about the `t` shortcut when a task is opened? I don’t normally use that functionality so could you test this please?

In `todoist-shortcuts.js` replace L1598, which should be
`      withUniqueClass(taskView, 'task-due-date-button', all, click);`
with
`      withUniqueTag(taskView, 'span', matchingText('Due date'), click);`

This seems to work for me.

**Comment by jakelfreeman** [comment]
Strange, it's working for me now in v5087, not sure what the issue was in v5085, but this is the first instance I can recall where the plugin has been fixed by a Todoist update.
