### ISSUE TITLE
Multiple things broken (e.g.: close pane) when task opened in v5085

### ISSUE THREAD

**Issue by champagnealexandre** [mgsloan/todoist-shortcuts#269]
Let’s say I open a task with the `i` key, then a lot of things seem to break. Pressing `i` again to close the task pane yields:

```
todoist-shortcuts:"Couldn't find unique descendant matching query""button[aria-label=\"Close modal\"]"", instead got"null
"
getStack@user-script:14:5529:22
warn@user-script:14:5512:30
withUnique@user-script:14:5593:11
@user-script:14:2640:17
withUnique@user-script:14:5591:15
taskViewClose@user-script:14:2639:15
@user-script:14:6301:39
_fireCallback@user-script:14:634:25
@user-script:14:703:34
@user-script:14:1056:37
@user-script:14:763:27
@user-script:14:930:34
genericKeyHandler@user-script:14:6394:38
s@https://todoist.b-cdn.net/assets/vendor~authentication~app~add~electron-login-229eafb5.1cb8b1bfb338fce472c180ac556f6f98.js:1:71428"
```

Edit: sorry I’m not smart enough with CSS/jscript to provide a fix myself. I wish I could do more.

Edit # 2: looks like I got it working!

Replacing L1553 of `todoist-shortcuts.js`,
`      withUnique(taskView, 'button[aria-label="Close modal"]', click);`
with
`      withUnique(taskView, 'button[aria-label="Close task"]', click);`
fixes the issue!

Now let’s wait and see what else they’ve broken...

**Comment by mgsloan** [comment]
Sorry about the delay!  Fixed in version 195
