### ISSUE TITLE
Sometimes task movement breaks nesting structure

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#29]
If you have a task above a nested tree of tasks, I've noticed that sometimes moving the task downwards moves it into the tree, disrupting the nesting structure.  Not sure what's going on there, I've tried to fix it, but with no progress so far.  I suspect that it is related to #28 or possibly even #27

**Comment by iswalker** [comment]
FWIW I've also noticed that moving a task which is a parent of nested tasks down in the list (Shift-Down) works fine going up, but when going down always sends it to the last position in the list.

Works fine if the list is collapsed, just not if expanded while moving around

**Comment by mgsloan** [comment]
@iswalker Ah, good point!  I don't use task nesting much myself, thanks for pointing that out.  As a workaround for now, it collapses the task tree before doing the movement.  Do you think that's an improvement?  Seems better to me.

Of course, the ideal fix to this would be to handle the movement properly, but this movement stuff is one of the fiddliest things in the whole extension.

**Comment by mgsloan** [comment]
I believe this issue is no longer relevant
