### ISSUE TITLE
Make 'navigate' support projects, labels and filters

### ISSUE THREAD

**Issue by mmazur** [mgsloan/todoist-shortcuts#3]
Navigation only supports jumping between projects. Labels and filters are not supported and they should be.

Background: I'm working on my "left handed navigation approach" (https://github.com/mmazur/todoist-shortcuts/commit/1ceaddc9ff0c783316382ca17aa0781447bde9e8), for which the basic philosophy is: right hand on mouse, left hand on keyboard, I want to be able to do useful stuff with only my left hand, which are complementary to what I'll be doing with the mouse. So a keyboard shortcut like 'F g a' gets me to my topmost filter, while 'D g a' gets my to my topmost label.

I have half of this working (S D F) and the other half to go ('g').

Btw: in some time todoist will [support pinning projects/labels/filters directly below "Next 7 days"](https://twitter.com/amix3k/status/961200820376219653). I'm trying to figure out an approach that won't be in conflict with this new functionality. I sort of suspect that once that's in place, just using 'g' with 'asdf' always going to those pinned projects/labels/filters will be enough, though I'm not sure of that.

**Comment by mgsloan** [comment]
Great, sounds good!  Yes, I don't currently have support for labels / filters partially because I don't have todoist premium yet and so I don't use those features.

**Comment by amix** [comment]
You should have premium now @mgsloan :)

**Comment by mgsloan** [comment]
I do indeed have premium now!! Thanks @amix :)

On Fri, Feb 23, 2018 at 1:34 AM, Amir Salihefendic <notifications@github.com

**Comment by mgsloan** [comment]
Fixed!
