### ISSUE TITLE
Shortcut request: Import from template

### ISSUE THREAD

**Issue by amahabal** [mgsloan/todoist-shortcuts#30]
Would love to have a shortcut for "Import from template", which should bring up the file selection menu.

**Comment by mgsloan** [comment]
@amahabal I'm not familiar with this option, where can I find it in Todoist's UI?

**Comment by amahabal** [comment]
On project actions, along with "Sort by date" etc. See attached screenshot.

![import](https://user-images.githubusercontent.com/50620/42068933-980d00ec-7b03-11e8-9995-845ab7bc86ba.png)

It is a premium feature, AFAIK.

**Comment by mgsloan** [comment]
Ah thanks, I hadn't seen some of the options under that menu.  Not sure what keybindings to give to these items.  Tricky to give everything a binding because then the keyboard gets rather busy.  So far I've mostly been focusing on things that are similar to gmail's bindings (which are rather vim-ey), because this way they will hopefully be reasonably familiar to people.

**Comment by amahabal** [comment]
On Thu, Jul 5, 2018, 1:48 AM Michael Sloan <notifications@github.com> wrote:

> Ah thanks, I hadn't seen some of the options under that menu. Not sure
> what keybindings to give to these items. Tricky to give everything a
> binding because then the keyboard gets rather busy. So far I've mostly been
> focusing on things that are similar to gmail's bindings (which are rather
> vim-ey), because this way they will hopefully be reasonably familiar to
> people.
>

You are right about not making too many bindings. Would it be possible to
add code to create such binding, and attach it to some key that you find
reasonable, but comment it out? That way, it is a no op for everyone, but
those who want to use it can load a local version with this action bound to
the key they want?

I would have submitted a patch if my JavaScript was good enough.

Thanks!

**Comment by mgsloan** [comment]
@amahabal Ah, yeah, this one was a bit trickier to write than most because there is no special class for the import from template menu item.  Also this code has my own idiosyncratic mini library to avoid depending on a library like jquery.

Anyway, I've pushed a commit implementing it :)

**Comment by mgsloan** [comment]
Closing this for now.  Going to continue with the arbitrary decision to not have a default keybinding for this.  Will be good to have the code around if / when a UI for customization is added.

**Comment by amahabal** [comment]
Works, thanks for your quick turnaround time!
