### ISSUE TITLE
Make visible the navigation (g) shortcut for favorite filters

### ISSUE THREAD

**Issue by amahabal** [mgsloan/todoist-shortcuts#31]
The "g" shortcut is super-useful, thanks!

I love that pressing "g" clearly displays what the next key would do: "i" for inbox and "g" for today, for instance. Labels and filters also get their own shortcuts, but for favorited labels and filters, this information is not displayed next to the label and filter.

**Comment by mgsloan** [comment]
Thanks, glad you like it!  I didn't know about this feature - I should be using it.

I've pushed a fix, it will be included in the next version of the extension.

**Comment by mgsloan** [comment]
Released in version 15 :)

**Comment by amahabal** [comment]
Thanks, it works!

These shortcuts go a long way toward keeping the overhead of using GTD to a minimum!

--Abhijit
