### ISSUE TITLE
[help] instruction is not clear

### ISSUE THREAD

**Issue by saikatm** [mgsloan/todoist-shortcuts#35]
in the readme file there to enter bulk mode or to select multiple task to press * key but nothing happens when i use * key as instructed in the readme file. i may be worng please let me know how to do it!!

![image](https://user-images.githubusercontent.com/9909763/43369000-bdca29d4-9383-11e8-86b7-e8ce2731037d.png)
![image](https://user-images.githubusercontent.com/9909763/43369002-c02ae54c-9383-11e8-96fb-7633967fdbf2.png)

**Comment by mgsloan** [comment]
Did you press `*` first and then `v` next?

**Comment by mgsloan** [comment]
Not sure how to make the docs clearer - closing

**Comment by AndyHickman** [comment]
Could you add a "+" sign? So it would read:
" * + 2 "

or another idea would be " * then 2 "
