### ISSUE TITLE
Sort by Name

### ISSUE THREAD

**Issue by GaryFurash** [mgsloan/todoist-shortcuts#36]
Can you add Sort by Name?

**Comment by mgsloan** [comment]
I can't. The existing sorting stuff is built into Todoist, so this would need to be added to Todoist.  In theory it could be possible to automate individual motions of tasks.  But the task motion stuff already has enough issues - https://github.com/mgsloan/todoist-shortcuts/issues/29 + https://github.com/mgsloan/todoist-shortcuts/issues/28 .  Trying to execute a ton of task motions to sort by name would be a lot of effort, and it probably wouldn't work very well.

Thanks for the suggestion, though!  I think you should make a request for this feature directly to Todoist

**Comment by GaryFurash** [comment]
Wait, you already CAN sort by name

![image](https://user-images.githubusercontent.com/15006133/43419765-c1427666-93f6-11e8-94a4-9809ab3a1021.png)

**Comment by mgsloan** [comment]
It's been released as part of version 18 of the extension

**Comment by GaryFurash** [comment]
Thanks Mr. Sloan.
