### ISSUE TITLE
A Task Can Accidentally Be Moved to Another Project

### ISSUE THREAD

**Issue by AndyHickman** [mgsloan/todoist-shortcuts#39]
I can't figure out how to reproduce the issue, but I'm 99% sure a task has been moved to another project when it is not a sub task and I have "moved it left" via the shift + H keyboard shortcut.

**Comment by mgsloan** [comment]
Ah, interesting!  Yeah, since todoist-shortcuts just simulates a mouse drag, and this will still try dragging left even if it's at level 1, it's quite conceivable that it drags it into a project on the left.

Thanks for the bug report!

**Comment by mgsloan** [comment]
Fixed!  Will be released soon. Thanks again for the bug report.

**Comment by mgsloan** [comment]
Released with version 19!

**Comment by mgsloan** [comment]
@AndyHickman Thanks!  Not sure, actually, I think it depends on your browser settings

**Comment by AndyHickman** [comment]
Michael,
You may already be aware of this but "shift + h" and "shift + l" are not
working at all. I'm also noticing that "a" (adding a task to the bottom of
the list) is not working either. I'm using Chrome 68 and have version 19
installed. Todoist version 913.

**Comment by mgsloan** [comment]
Thanks for the heads up!  I hadn't realized that, I don't use task nesting much in my everyday use.

It turned out that my workaround for https://github.com/mgsloan/todoist-shortcuts/issues/40 triggered a surprising inconsistency in the mousetrap library: https://github.com/ccampbell/mousetrap/issues/430

**Comment by mgsloan** [comment]
I've released version 20 with the fix :)

**Comment by AndyHickman** [comment]
👌 Perfecto
