### ISSUE TITLE
Todoist shortcuts don't work with Firefox

### ISSUE THREAD

**Issue by Dennis8** [mgsloan/todoist-shortcuts#40]
Hi,

I've tried using Firefox 61.0.1 with Ubuntu 18.04 with this add-on installed.
However the keyboard shortcuts don't seem to work, not even the single key ones (h,j,k,l).
Iv'e tried the following:
- Change my todoist language to English.
- Disable every other extension I have.
- Refresh Firefox.

It still doesn't work. Any ideas?

**Comment by mgsloan** [comment]
Whoah, good catch, I can reproduce the problem.  I wonder how long it's been broken on firefox.  I typically use it with chrome.

**Comment by mgsloan** [comment]
I've spent an hour trying to debug this, but it's very puzzling.  Mousetrap's keydown and keyup events are getting called, but the keypress events aren't getting, and that's the one that matters here.

The weirdest thing is that if I put event breakpoints on the keypress events, there are no breakpoints.  If mousetrap doesn't register its handler, then the breakpoint does get invoked.  I noticed that the `addEventListener` call has been monkeypatched by some lib called raven from https://github.com/getsentry/sentry-javascript .  So my theory is that the monkeypatched function is malfunctioning.

The hack workaround for now is to instead use the keypress event on firefox.  This means no key repeat for firefox users, which can suck for usage of j / k.

**Comment by mgsloan** [comment]
Ok, actually miraculously switching the mousetrap bind over to use keydown fixed the issue entirely.  Surprisingly, key repeat still functions, which is quite unexpected.  I won't dig into the details of why that's happening, instead just happy to declare victory.

**Comment by mgsloan** [comment]
Released as version 19!
