### ISSUE TITLE
Chrome Extension Conflicting with "a" & "A" Todoist Shortcuts

### ISSUE THREAD

**Issue by AndyHickman** [mgsloan/todoist-shortcuts#41]
I recently noticed that the Todoist's shortcuts for adding an item to the top or bottom of a list ("A" or "a") doesn't work. At first I thought this was a bug in Todoist itself, but the problem doesn't exist when I temporarily disable the todoist-shortcuts chrome extension.

**Comment by mgsloan** [comment]
Ah, good catch!  I almost always use `o` / `O` for adding tasks, so I didn't notice.

Fixed!  Will be released later today as part of version 21

**Comment by tomas-ab** [comment]
just adding that I use Firefox 62.0.2.
