### ISSUE TITLE
g doesn't show shortcuts for all items

### ISSUE THREAD

**Issue by GaryFurash** [mgsloan/todoist-shortcuts#44]
When I do a g (to move to a different project) I only see shortcuts for some of the items

![image](https://user-images.githubusercontent.com/15006133/45828024-79e13800-bcac-11e8-8a9b-d63524c55c85.png)

**Comment by mgsloan** [comment]
Hmm, curious!  I do not see that behavior in either chrome or firefox.  Which version of todoist-shortcuts + what browser are you using?  (version 21 is the latest)

**Comment by GaryFurash** [comment]
I tried clearing the cache by logging out and removing cookies then starting again.

**Comment by mgsloan** [comment]
Hmm, well that's a real mystery.  In the past such things have occurred due to CSS styling affecting display of the notes.  Could you please check if that's what's happening?  Perhaps a userstyle is changing CSS? (unlikely but possible)

**Comment by GaryFurash** [comment]
How do I check this? I don't have any custom user style things.

**Comment by GaryFurash** [comment]
FYI I just added the todoist plugin to firefox and I get the same behavior 

![image](https://user-images.githubusercontent.com/15006133/45903857-f274f100-bd9f-11e8-97af-00a432da4ab5.png)

**Comment by GaryFurash** [comment]
premium

**Comment by GaryFurash** [comment]
I checked and it's just those specific projects

If i create a new project then the gv key makes a shortcut for it.

If I then rename the project to the same name as the non-working projects, it doesn't work. No shortcut

**Comment by boemska-nik** [comment]
Not looked at how this works in the code, but I had a suspicion it might be something to do with how certain UTF8 emoji characters in the project names are parsed to create the shortcut combinations. Check this out - just created calendar with 📅:


![image](https://user-images.githubusercontent.com/11962123/45926984-a9e64080-bf23-11e8-90fd-0fc97d557881.png)

**Comment by boemska-nik** [comment]
Some more info: 

U+1F5C4, unicode v7 filing cabinet -> works 🗄
U+1F4C5, unicode v6 calendar -> doesn't work 📅
U+1F5D3, unicode v7 spiral calendar -> works 🗓

@GaryFurash, maybe try some characters that are down as Unicode v7 [on this site](https://www.compart.com/en/unicode/U+1F5D3) and report back

![image](https://user-images.githubusercontent.com/11962123/45927120-27ab4b80-bf26-11e8-9f6b-f69ce6dc2887.png)

**Comment by GaryFurash** [comment]
yes that was the problem. Thanks!

-- gary furash | furashgary@gmail.com, 520-907-2470

**Comment by mgsloan** [comment]
Ah, thanks for narrowing down the problem!  I'd assumed that only one `span` element would occur within the project label, but turns out this assumption did not hold in the presence of emoji.

I've released version 23 which fixes this issue
