### ISSUE TITLE
Need a way of buying beer 

### ISSUE THREAD

**Issue by boemska-nik** [mgsloan/todoist-shortcuts#45]
Your todoist-shortcuts project is incredibly well executed and has (along with Amir's awesome product)  transformed my professional productivity and substantially improved my life. For that, I want a mechanism by which to buy you a beer. 

How can I buy you a beer?

**Comment by mgsloan** [comment]
@boemska-nik I've created an account with https://www.buymeacoffee.com/mgsloan - thanks for the idea!
