### ISSUE TITLE
New Todoist Scheduler Update Break the Extension

### ISSUE THREAD

**Issue by saikatm** [mgsloan/todoist-shortcuts#49]
Todoist Have Updated The Date/Time Scheduler For Todoist Web App.
New Scheduler is Awesome but it breaks the functionality of the Extension.
Hope You will get on this soon! Thanks.
Scheduler is live on http://beta.todoist.com
![image](https://user-images.githubusercontent.com/9909763/46822341-db2a9180-cda8-11e8-8e82-e5b73db5203d.png)

**Comment by mgsloan** [comment]
Thanks for the heads up!  For me, that only appears on beta.todoist.com .  It occurs to me that I should really be using the beta, so that the extension is ready for such changes.

**Comment by mgsloan** [comment]
Ah, I see that you mentioned beta.todoist.com in the issue, I missed that before.  I've released a version that has a fix for this, v28.  Still works with current todoist as well, of course.

**Comment by saikatm** [comment]
Suck a Rock star you are! 🌟
