### ISSUE TITLE
Key assignment philosophy

### ISSUE THREAD

**Issue by mmazur** [mgsloan/todoist-shortcuts#5]
I'd like to make something explicit before I start sending more patches. My desktop system is configured in a certain way wrt how I use mouse + keyboard. It boils down to two rules:
1. Frequent actions useful when I have my right hand on the mouse should be doable with my left hand alone. Some examples: caps+1…4,q…r – switch virtual desktops; caps+f – launches a terminal; caps+d – show desktop; alt+tab – obviously; alt+s/f – in chrome switch tab left/right (I have Alt also bound to my mouse to not kill my wrist)
2. Less frequent actions or ones that have a reasonable expectation of my right hand also being on the keyboard can require both hands. Examples: caps+hjkl – emulates arrow keys; caps+i – Del;

I would like todoist-shortucts to have the same philosophy. If you agree, great. If not (or you're just not interested in the subject to the same extent I am :), that's also fine – I'll just use my changes privately.

Here are some suggestions on what such an approach would imply:
- jumping between inbox/today/7days and labels/projects/filters would only use lefthanded keys; currently I'm using shift+ for this, so WER is inbox/etc. and SDF is project/etc., though I'm not sure this is optimal.
- 'g' + keys would need to obey this. So in the example above if 'shift+w' is always Inbox, then 'g w' would need to be as well.
- 'g' nav keys would always start with the lefthanded keys, only once those are used up, go with the righthanded ones. 
- ideally a user would be able to memorize something like 'shift+f, g s' (or 'g f, g s') to always end up on their second filter from the top.
- not sure how to reconcile the above point with the soon-to-be project pinning; it stops being doable if there's an arbitrary number of pinned projects in the top level nav; two options I came up with: left-handed predictable shortcuts are only for top level/pinned projects; anything below is right-handed or: have two navigation modes 'g' and 'G' – one does top level/pinned, and the other does whatever's in the projects/labels/filters box.

**Comment by mgsloan** [comment]
Thanks for taking the time to type this up!  My preferred computer usage is no mouse at all.  I use tools like [keynav](https://github.com/mgsloan/keynav), [xmonad](https://github.com/xmonad/xmonad), and [vimium](https://github.com/philc/vimium) to make it so that I barely need the mouse for anything.

My preferred implementation for jumping to projects / labels / filters would actually be to use a prefix of the project / label / filter name.  This way the keypresses would be mostly stable.

> I would like todoist-shortucts to have the same philosophy. If you agree, great. If not (or you're just not interested in the subject to the same extent I am :), that's also fine – I'll just use my changes privately.

The keypress philosophy I'm using here is to emulate existing tools as much as possible.  Particularly, I figure that much of the audience for this would probably use gmail shortcuts if they use gmail (which many people do).  So, I mirrored gmail shortcuts nearly as much as possible.  The only exception I made was to have `m` mean "move to project" rather than `v` which would be closer to the gmail shortcut.  I believe they needed to pick `v` because `m` was already taken by "mute".

So, I don't think I want to have todoist-shortcuts default to your keyboard scheme.  However, I do not want to discourage you from making changes to the code and getting them merged.  If you want to add your scheme, then we can do something like

```javascript
   var KEYBINDING_STYLE = 'gmail';

   var KEY_BINDINGS;
   if (KEYBINDING_STYLE === 'gmail') {
     KEY_BINDINGS = [ ... ]
   } else if (KEYBINDING_STYLE === 'left-hand') {
     KEY_BINDINGS = [ ... ]
   }
```

To make it even more seamless, could consider having the following:

1. A configuration page for the extension that allows you to switch between the vim-ey gmail style and the left-hand style.
2. Ideally if surfaced in the extension options, a `LeftHandReadme.md` file documenting the layout

This is the first browser extension I've written, not sure how to add options to it.

**Comment by mmazur** [comment]
Ah, now I get why you've defaulted to WHAT_CURSOR_APPLIES_TO = 'all'. :)

Gmail is a great example for this conversation. Look at gmail's shortcuts from the point of view a person alternating between all keyboard and mouse+keyboard:
- right hand is for 'pointing' at stuff, so you can use either your mouse to select/navigate or you use the right hand keys: u, k, j, o/enter, ','
- the most commonly used actions are (to the extent possible) left handed: select, archive, star, spam, delete, reply/all, forward.

So even if you don't go all-keyboard, but use (like a typical person does) mouse+keyboard, you get a significant boost in productivity from having just your left hand on the keyboard and being able to immediately take action on any email you select with your mouse.

Seen from this perspective, 'move' should not be 'm', it really should be 'v'. So in the following scenarios:
- both hands on keyboard: 'v', then type in/use arrows to select a project
- keyboard + mouse: 'v' and then click with the mouse the project you want to get to.

Using 'm' slows down the operation for anybody not using the keyboard exclusively, which will be the minority of people.

I understand the option of having selectable keymappings, though I would rather start with getting the base keymapping as universal as possible (a'la gmail) and only diverge slightly from that if I really need to.

**Comment by mgsloan** [comment]
That sounds good to me!

Yes perhaps move can be switched back to `v`.  I figured `m` was more mnemonic but perhaps there is more into it than just that.

**Comment by mmazur** [comment]
Though looking from this perspective, the 'g' nav should likely be on the right hand, with the the 'g' key being used for something more useful. I'll have to think this through some more…

**Comment by mmazur** [comment]
Ok, I gave this some thought and here's what I came up with. But first, a few assumptions:
1. Project/filter/label pinning is coming and we can assume people will flock to it (I sure as hell will; learned tampermonkey myself just to add it as a simple script a few weeks ago). This means the top level nav menu will not be a static 3, max 4 item list: people will be cramming 15 items in there easily.
2. Projects are likely the most popular item, but labels and filters should also be first class citizens.
3. Since the split left-action, right-navigation should mostly hold true, jumping between projects/filters/labels should be mostly initiated with the right hand, since if you're using the mouse, you might as well click what you need.

Taking into account all of the above, here's what I came up with as a default:
- 'g' is used for navigation, but it's only useful for the top level nav menu. This stays left-handed as an exception, since it's sort of a 'quick nav' key: inbox/today/pinned projects will be by definition the most used ones, so it makes sense to be able to quickly punch 'g a' to get to, say, the inbox, or 'g v' to get to your second pinned project. Note: letter ordering here is left hand centric, because this is the one nav key that assumes your right hand might be on the mouse.
- 'P'/'L'/'I' - are used to navigate between **P**rojects, **L**abels and f**I**lters. They work in the following way: you punch 'I', todoist switches to filters, then (if possible) scrolls the left panel such that only the filters are visible (top level nav menu gets hidden), then it shows available letters, but *only* on the filters, it ignores the top level nav.
- (of course 'g' could optionally sort of keep the current behavior, in that it starts with the top level nav menu, but also allows navigation through whatever is currently selected: projects/filters/labels.)

Examples (just examples, I'm not set on letter ordering here):
- 'g q' – inbox
- 'g r' – 2nd pinned project (possibly 1st if team inbox is visible)
- 'g d' – 5th pinned project (possibly 4th if team inbox is visible)
- 'P q' – always first project (doesn't matter how many are pinned)
- 'L u' – around ~17th label (doesn't matter how many are pinned)

**Comment by mmazur** [comment]
Your code is fault tolerant enough, that I was able to prototype this rather easily (https://github.com/mmazur/todoist-shortcuts/commit/ff2c085473e9ad289453701fcb787e9169b8c38a) and it actually works. Everything produces a ton of console errors, labels and filters don't actually show their assigned keys, 'L' key was already taken, so I switched to 'B' plus I suspect oldNavigateOptions might not correctly handle having four different nav lists ran against it, but other than all that I can just type 'I a' and end up on my first filter. And if they keep pinned projects in the same top nav list as inbox/today/etc., this should handle them just fine out of the box. :)

Thoughts?

**Comment by mgsloan** [comment]
Glad the experiment worked out, sounds interesting!  Indeed, I tried to make the code as fault tolerant as possible, an external observer might be a little puzzled why I used so much `try` + `finally`, but I wanted it to fail gracefully!  I also do not usually write javascript, though I know it fairly well.  I usually write Haskell and there I am used to a much higher degree of reliability.

I agree with making the `g` nav prioritize the left hand keys, but still use the right hand keys after those are used up.

To me it allows switching between navigating project / labels / filters, perhaps defaulting to the last thing that was navigated to?  For my current usage I don't use labels or filters at all, I want to keep the keystrokes to navigate to a project at a minimum.

**Comment by mmazur** [comment]
Ok, so:
- Letter ordering goes left hand first, then right hand
- 'g' starts with the top level nav, then goes after the currently active tab, be it projects/labels/filters (so for somebody only using projects, like you, 'g' on its own might be enough for all nav needs)
- P/B/I switch between projects/labels/filters and assign keys only to them, ignoring top level nav

Agreed? If yes, I'll start with getting the letter assignment functions to be able to handle not just projects, but whatever is currently active.

Btw: you might not be using labels and filters now, but with the pro account, you're likely to eventually get there. Simple example of filters: "Today Work" and "Today Other" – makes it much easier to focus on my work having these two separate instead of using the global "Today" (especially once they'll be pinnable).

**Comment by mgsloan** [comment]
Sorry, I don't think the default keybindings are going to be changing much from the current setup.  It seems like many of the important actions are on the left hand already, which works nicely when using the mouse to indicate which task the action should apply to.

Perhaps someday in the future the shortcuts will be configurable!  Till that day, it is always possible to use a locally customized version of the extension as described in https://github.com/mgsloan/todoist-shortcuts/#how-to-customize-keyboard-shortcuts
