### ISSUE TITLE
Indenting task no longer works

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#50]
Indenting a task inwards no longer works - it properly drags the task, but the rectangle indicating where the task will drop does not move inwards.  I believe this is due to a change in the mouse events that Todoist is expecting.

Unfortunately, after spending some time looking at the problem, I haven't been able to easily figure out the issue.  So, for now documenting the problem.

**Comment by mgsloan** [comment]
A hack occurred to me - could automate the following sequence:

1. edit task
2. ctrl+right arrow
3. enter

Hah!

**Comment by lovetofail** [comment]
Hi. It also always moves subtask to the very left. Instead of moving it only one level left.
I tried slowing down the animation at "animateDrag". It looks weird but I still couldn't figure out the problem.
"2. ctrl+right arrow" - tried emulating it with "KeyboardEvent" but failed.

**Comment by mgsloan** [comment]
Happily, this now seems to be fixed!
