### ISSUE TITLE
[help] bulk smart reschedule

### ISSUE THREAD

**Issue by mrderiuzz** [mgsloan/todoist-shortcuts#53]
how do I reschedule multiple selected tasks to the date that smart scheduler suggests? 

Is there any way to bypass the smart schedule popup so that I can just select, schedule, smart rescheduled? It works like that for a single task (x, then t and then s for smart reschedule)? 

I trust AI-scheduler suggests a good date :)

**Comment by mgsloan** [comment]
Implemented!

> * When scheduling multiple items, `s` now opens the smart
>  scheduler. Within the smart scheduler, `enter` applies the updates,
>  and `escape` cancels.

**Comment by mrderiuzz** [comment]
works like a charm. Many thanks!
