### ISSUE TITLE
Missing shortcut: Add project

### ISSUE THREAD

**Issue by amahabal** [mgsloan/todoist-shortcuts#55]

**Comment by amahabal** [comment]
Perhaps this exists, but I was unable to find this. Is there a way to add a project via keyboard? 

Thanks!

**Comment by mgsloan** [comment]
@amahabal There isn't a keybinding for it, or other project manipulations for that matter.  For my workflow, project manipulation is uncommon enough that I don't mind using the mouse or mobile interface for it.

**Comment by amahabal** [comment]
Thanks for the explanation, and you are right that it is used relatively infrequently. I felt the strong need for it as I started setting up my system afresh, but already in a week it will be rare again.

Closing this.
--Abhijit
