### ISSUE TITLE
Shortcuts for "Todoist for Gmail"?

### ISSUE THREAD

**Issue by mgsloan** [mgsloan/todoist-shortcuts#61]
I recently started using the [Todoist for Gmail](https://chrome.google.com/webstore/detail/todoist-for-gmail/clgenfnodoocmhnlnpknojdbjjnmecff?hl=en) extension.  It's pretty nice!  And as of v41, todoist-shortcuts works within the embedded Todoist.

However, of course I would like keyboard shortcuts.  Specifically:

* A shortcut to add the current email as a task.  I'm thinking `q` while gmail is focused.

* A shortcut to switch between gmail and the todoist frame.

* Possibly a shortcut to collapse the todoist frame.  It might be cool to generally have keybindings to control gmail inline frames.

I *think* this should be possible, though iframes can be tricky.

# Include directly in `todoist-shortcuts`?

One decision to make here is whether it should be included directly in `todoist-shortcuts`.  The alternative is to create a new, separate extension.

## Pros for direct inclusion

* No need to install another extension, conveniently just there.  Possibly more users with access.

## Cons for direct inclusion

* Would need to add access to gmail to the urls that todoist-shortcuts is active on.  For the security conscious, it would probably be better to have only a very small extension with permission to read/modify gmail.

* By not having an opt-in, people might not realize the keyboard shortcuts exist.

## Initial conclusion

Should probably be a separate extension.  What do y'all think?  Maybe folks don't care about adding permissions to read/write gmail?

**Comment by mgsloan** [comment]
Ahh, I thought about it a bit more, and I think it's possible to eliminate the main problems with direct inclusion.  It looks like it's possible for an extension to ask for extra permissions after installation.  Not sure where to put the opt in UI.  Perhaps in Todoist's settings menu.

To satisfy the super security conscious, the code running in gmail could also be kept minimal by having `inject.js` check the domain the extension is running on, and inject a much smaller script when running on gmail.

**Comment by grantgordon** [comment]
Did this ever happen? I'd love this feature.

**Comment by sazwqa** [comment]
+1 would love this feature 

**Little Background**
Before discovering Todoist -- I was using Shift + T for Google Tasks (which was garbage), but loved the gmail + task integration.

Also, no other todo list tool comes close to Gmail integration -- Asana's integration is crap and I haven't seen any other.

**Comment by mgsloan** [comment]
Thanks for letting me know about your interest! It hasn't happened yet, and it's uncertain whether it ever will.  These days for me there isn't as much need for me to integrate gmail and Todoist, so I don't anticipate implementing it soon.

**Comment by mgsloan** [comment]
I don't think I'll implement this, closing as wontfix.

**Comment by igormoreno** [comment]
Hi. May I ask what is your workflow for email and todoist? I'm curious because you said you don't see the need for this feature. (love this extension by way... really helps me a lot!)

**Comment by mgsloan** [comment]
@igormoreno I don't use the Todoist for GMail extension.  If I do want to reference an email in a task I use a keyboard shortcut bound to the "current tab: [title](url)" action of the [Copy as Markdown](https://chrome.google.com/webstore/detail/copy-as-markdown/fkeaekngjflipcockcnpobkpbbfbhmdn?hl=en) extension, and then paste it into todoist.

**Comment by igormoreno** [comment]
interesting... thank you
