### ISSUE TITLE
An alternative to todoist-shortcuts in Todoist Desktop Application

### ISSUE THREAD

**Issue by pinusm** [mgsloan/todoist-shortcuts#62]
Perhaps you could mention in the readme an alternative to [kevinjalbert/todoist-shortcuts-nativefier](https://github.com/kevinjalbert/todoist-shortcuts-nativefier) for using todoist-shortcuts in a desktop application, where one could install your extension in chrome, and then create a ['open as window'](https://www.howtogeek.com/403399/how-to-make-chrome-open-as-window-shortcuts-now-that-google-killed-them/) shortcut, for a native-esque feeling.

**Comment by mgsloan** [comment]
It's been in the readme, but for some reason the header was h2 instead of h1.  I've updated it and the header - https://github.com/mgsloan/todoist-shortcuts#todoist-shortcuts-in-electron-application

Thanks for making todoist-shortcuts-nativefier!

**Comment by pinusm** [comment]
Thanks for replying!
Despite the h2 header, I did see this section in the readme. 
What I meant was to suggest an alternative TO [kevinjalbert/todoist-shortcuts-nativefier](https://github.com/kevinjalbert/todoist-shortcuts-nativefier) that does not require anything more than an updated version of Chrome (V72+). I find this is simpler than having to build kevinjalbert's solution, although it offers less customization possibilities.

**Comment by mgsloan** [comment]
Ohh for some reason I mixed up you and @kevinjalbert , and didn't read your text very carefully.  I've updated the readme in 6781bfc - how's that look?

**Comment by pinusm** [comment]
Perfect! thanks!
