### ISSUE TITLE
[Feature Request] add option to ignore the keyboard layout

### ISSUE THREAD

**Issue by pinusm** [mgsloan/todoist-shortcuts#63]
In Vimium, a useful feature for those using multiple keyboard layouts is ['Ignore Keyboard Layout'](https://github.com/philc/vimium/commit/62b36b3bcce6ab1f5b8735ecf1335e40600c5617), added in 1.60.  Adding this functionality to todoist-shortcuts would make adding/editing tasks in non-Latin languages much easier, as a layout switch-in and switch-out could be saved.

At the moment, adding a task using multiple layouts looks like this (worst case, as the initial layout is non-Latin):
`Alt`+`Shift` - switch to English
`q` - open quickadd dialog
`Alt`+`Shift` - switch to Hebrew
`להציע להתעלם מפריסת מקלדת` - actual todo text
`Enter` - save the new task.

if I'd like to add a P.S comment:
`Alt`+`Shift` - switch back to English
`c` - open comment dialog
`Alt`+`Shift` - switch to Hebrew
`להיות טרחני לגבי זה, אבל לא מדי` - actual comment text
`Esc` - save the task.

I just started using the extension, and it looks great!
Many thanks!!

**Comment by mgsloan** [comment]
Glad you appreciate the extension!

I don't use any non-latin layers, not sure how I would set that up.  From a skim of the PR I'm not sure how to adapt the code.  I'd probably merge a PR adding such a feature, though.  I think it might need to be a change to [mousetrap](https://github.com/ccampbell/mousetrap) - note that todoist-shortcuts uses a forked version of mousetrap - https://github.com/mgsloan/mousetrap

**Comment by mgsloan** [comment]
Would be open to PRs addressing this, but I'm not going to implement this, so closing as wontfix.
