### ISSUE TITLE
Can't move to nested tasks in filter or search list

### ISSUE THREAD

**Issue by brettmiller** [mgsloan/todoist-shortcuts#64]
While viewing a task list from a filter or search when there are sub-tasks you can use h/l to open and collapse the parent, but you can't navigate up or down to the sub-tasks with j/k. If there are tasks at the same indention as the parent below the sub-tasks it jumps to the next task at the same indention as the parent when navigating down (j) and back to the parent when navigating up (k).

**Comment by mgsloan** [comment]
Thanks for reporting this issue.  It's now fixed in version 46.

While looking into it I encountered some other issues - #65 - where the best resolution seemed to be to only use the blue cursor, rather than attempting to use the drag handle.
