### ISSUE TITLE
Feature Request: Keep multiselection after performing action on selected items

### ISSUE THREAD

**Issue by igor-kupczynski** [mgsloan/todoist-shortcuts#69]
Hello :) not sure if this is more of a bug or a feature request. When you select multiple items (e.g. with `x`) and perform an action (e.g. `@` or `y`) after the action is performed the items are no longer selected.

I often select multiple tasks to adjust the labels or to label them and then move to a project, e.g.
1. Select more than one task
2. `@` add label `foo`
3. Select the same tasks again
4. `y` remove label `bar`

Ideally I'd like to get rid of step 3. Would this be possible?

**Comment by igor-kupczynski** [comment]
BTW this is my first interaction with this repo -- wanted to say *thanks* for creating the plugins. They greatly enhance the usability of todoist and save me a lot of time every day!

**Comment by mgsloan** [comment]
Hi @igor-kupczynski my bad for not responding to this issue earlier, I seem to have not created a task for it, heh.

I agree that this would be nice.  It may be a bit tricky to identify when adding a label has been completed and restore the selections at that point.  I think it should be feasible to add a keybinding which restores the last recorded selections.  Heck, could even ponder having an undo/redo selection stack, wouldn't be very hard.

**Comment by kellyarwine** [comment]
Seconding this request.  Big fan of this extension.

**Comment by mgsloan** [comment]
Might get around to this at some point, I added it to my todoist-shortcuts list inside my Todoist :)

**Comment by mgsloan** [comment]
It's a good idea, but I don't think it's going to be implemented.
