### ISSUE TITLE
g does not expand hamburger menu on todoist small-screen mode (951/952?)

### ISSUE THREAD

**Issue by boemska-nik** [mgsloan/todoist-shortcuts#70]
Not sure how new this is, and tbh not sure if I prefer it this way or not (!), but the g key doesn't expand the collapsed section navigation menu in narrow app mode, which I'm sure it did before. The nav shortcuts themselves do still work though.

**Comment by mgsloan** [comment]
Good catch!  Looks like a change in the todoist CSS.  I've uploaded a new version with a fix to this issue.
