### ISSUE TITLE
v956 broke shortcuts?

### ISSUE THREAD

**Issue by mrderiuzz** [mgsloan/todoist-shortcuts#72]
suddely this morning my shortcuts just broke. reinstalling didn't help. Please help, I can't work without that :D

**Comment by mrderiuzz** [comment]
todoist-shortcuts.js:43 Uncaught TypeError: Array.concat is not a function
    at todoist-shortcuts.js:43
    at todoist-shortcuts.js:3840

**Comment by abelthomas** [comment]
@mgsloan when will this fix be deployed to the Chrome extension? I upgraded to `v956` unknowingly, and have been struggling without these shortcuts for 3 days too long now... 😱

**Comment by mgsloan** [comment]
@abelthomas Hmm, perhaps you need to update the extension?  Version 53 of the extension includes the fix and was uploaded a few days ago.
