### ISSUE TITLE
Same task in two places in filter causes loop

### ISSUE THREAD

**Issue by 8utl3r** [mgsloan/todoist-shortcuts#77]
I have a custom daily filter set up and the same task will show up in two different sections. When I scroll down the list I will go past the first instance without trouble. However, when I try to scroll past the second instance the cursor pops up right below the first instance like I had just scrolled past it. When the cursor is on one of the tasks is shows on both.

**Comment by mgsloan** [comment]
Hi @8utl3r thanks for reporting.  I can certainly see how that would cause problems.  I don't quite follow how to setup a filter that causes the problem, though, can you please provide details?

**Comment by mgsloan** [comment]
No response, so closing.
