### ISSUE TITLE
Shortcuts don't work on win10/chrome, yet a competitor plugins works

### ISSUE THREAD

**Issue by jcpeterson** [mgsloan/todoist-shortcuts#78]
Vimium is turned off. Any other ideas?

This plugin works: https://chrome.google.com/webstore/detail/todoist-keyboard-navigato/kglgmdpjkdbdgidekpklgkibnfgagejm

**Comment by mgsloan** [comment]
Hmm, are there any errors in the developer console (open via ctrl+shift+i)?

**Comment by jcpeterson** [comment]
Thanks for getting back. Don't see any errors in the console (had to click on it after ctrl+shift+i as esc didn't do anything). To be clear, I'm using the popout window from the chrome plugin as the main window doesn't even have all of the selectable elements (e.g., Inbox).

**Comment by mgsloan** [comment]
No problem, thanks for reporting the issue!  I do not have convenient access to any windows machines at the moment so it's a bit tricky to diagnose.

> I'm using the popout window from the chrome plugin

Hmm, so opening developer tools for todoist-shortcut's background page?  Errors won't show up there, instead you'd need to open developer tools for the todoist window.  You can access those by clicking the menu dots on the top right, hovering "More tools", and clicking "Developer tools"

**Comment by jcpeterson** [comment]
Oh, I see, thanks. The shortcut plugin only works with the web app at `https://todoist.com/app` in a browser tab. 

There is also an official todoist chrome plugin that has both dropdown and popout versions of the app, which appear to be identical (although now prefer the web app now that I know about it). I think the url is `chrome.todoist.com/app`. It's not clear from your plugin page that this is its only use case. The other plugin I linked, which has much less functionality, works with the chrome plugin as well. You could make a note of this in the description, but it may not be too much work to extend usage to the chrome plugin (perhaps just include the alternate url?).

Also, I'm betting the Windows app is not much different from the web app. It would be nice to have these shortcuts there as the app can be brought to focus with a single global shortcut unlike a browser tab.

**Comment by mgsloan** [comment]
Ahh, yes, the linked plugin has

```
"matches": [ "https://todoist.com/app*", "https://*.todoist.com/app*" ],
```

Whereas this plugin has

```
      "matches":
        [ "https://todoist.com/app*"
        , "https://beta.todoist.com/app*"
        , "https://gmail.todoist.com/app*"
        ],
```

Cool, thanks for helping me track this down.  I will hopefully make the fix later today.

**Comment by mgsloan** [comment]
I believe it should be fixed now!  Thanks for reporting the issue and iterating with me on this.  Fix released in version 55.

**Comment by jcpeterson** [comment]
Thanks!
