### ISSUE TITLE
"Keys must be unique" error on favorited filters

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#79]
I have an "Assigned to others" filters that I added to my favorites. When I press 'g', this error pops up on the console: "keys ao must be unique."

Looking at the code, "Assigned to others" is a special name that always gets assigned the key "ao". So I guess the filter and its entry in the favorites list are treated as duplicates, causing that error.

It may be innocuous but it does create some log spam. In particular, I opened the console to look into why the "tp", "tf", and "tl" keys weren't showing up anymore, but instead I got a spate of this.

**Comment by mgsloan** [comment]
Thanks for reporting the issue and looking into it!  I've uploaded version 56 which I believe should resolve it, but I admit I haven't actually tested it.  Please let me know if the new version behaves well for this case.

**Comment by ismig** [comment]
I'm not seeing the error any more, so I'd call it good. Thanks for the fix!
