### ISSUE TITLE
tp,tf,tl keys aren't appearing (as of version 757?)

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#80]

**Comment by mgsloan** [comment]
Hi, I don't know what those keys are, could you please clarify?  Thanks!

**Comment by mgsloan** [comment]
Ah, I see your previous issue, lets have the discussion there.

**Comment by ismig** [comment]
Sorry, I was too terse. I meant the hard-coded keys for the three panels: 'tp' for projects, 'tl' for labels, and 'tf' for filters. Those seem to have disappeared (although keys for individual projects, labels, and filters work fine).

![tptltf](https://user-images.githubusercontent.com/40349450/61176085-843c2d80-a56f-11e9-9b95-15bdce42347b.png)

**Comment by mgsloan** [comment]
Ahh, I see, thanks for reporting and clarifying!  I think those sequences weren't recognizable to me because the filters / labels I do use are favorited and so I don't usually toggle the sections.

I'll look into this soon!

**Comment by mgsloan** [comment]
Fixed in version 57.  Thanks again for reporting the issue
