### ISSUE TITLE
Certain Shortcuts No Longer Work After using "g" to Jump

### ISSUE THREAD

**Issue by GraphicThinkPad** [mgsloan/todoist-shortcuts#81]
Ever since Todoist version 959, there's some strange behavior. After using the g key to jump to a new project, hitting keys like T (note the capital) or v where you type in the command no longer work. They still bring up a menu, but you cannot type in them like you should be. This gets fixed once you refresh the page but the behavior repeats itself after another g jump.

I'm on Chrome 72 if that helps.

**Comment by ErikOsterud** [comment]
Noticed a similar issue with the shift+3 (delete) command. With the new version it works a time or two, but then the page needs to be refreshed to work again.

**Comment by mgsloan** [comment]
I just started seeing these problems today too, will hopefully take a look at it this evening.  Traveling this weekend and packing this evening so unfortunately there's a possibility I won't get around to fixing it.

**Comment by mgsloan** [comment]
I didn't figure out why exactly `T` and `v` started misbehaving.  I think I found a fix though and released it in version 59.  Does the issue appear to be fixed?  Please comment / reopen if not.

I did notice another symptom, which is that the cursor isn't visible after switching projects.  The mechanism that notices when the cursor isn't on anything broke!  It expected that a DOM element with id `editor` would never be re-created, but it appears that is no longer true.
