### ISSUE TITLE
Keyboard shortcuts not ignored when a modal dialog is open

### ISSUE THREAD

**Issue by apoliveira** [mgsloan/todoist-shortcuts#82]
When a modal dialog is open and the cursor is not focused on an input field, the extension processes keystrokes as shortcuts.

As as simple example:
1. Begin a quick add task (**q**)
2. Realize you don't want to add it (**esc**)
3. Use any shortcuts while the "Are you sure you want to discard your current task" submodal is open.

In fact, simply opening the quick add modal and giving focus outside of the input field (but still in the modal) will create the same issue.

**Comment by mgsloan** [comment]
Thanks for reporting this issue!  I'd also noted down some strange behavior with cancelling the q dialog.  I'm currently traveling but should be able to look into this a couple weeks from now.

**Comment by mgsloan** [comment]
Finally fixed this!  The fix is included in version 62
