### ISSUE TITLE
Bulk Move Freezes Page

### ISSUE THREAD

**Issue by EvilistMonkey** [mgsloan/todoist-shortcuts#83]
When I hit *v everything freezes up. Can't type anything, can use mouse, can't use shortcuts. Nothing. Using the 'v' shortcut works just fine for single moves though.

**Comment by mgsloan** [comment]
Hey, thanks for reporting.  Are you still seeing this issue?  The "v" shortcut seems to work fine for me, perhaps it was a Todoist bug that got fixed.

**Comment by mgsloan** [comment]
Closing from now response.
