### ISSUE TITLE
Label-based shortcuts broken with Todoist Version 968

### ISSUE THREAD

**Issue by ErikOsterud** [mgsloan/todoist-shortcuts#84]
Thanks for the great extension!

It looks like with Todoist Version 968 that they have made some changes to Labels and the `@`/`y`/`#` command is no longer working (either standalone or in bulk). It looks like they moved Labels and some of the menu options to a different area in the multi-select as well.
![2019-09-04_07-42-42](https://user-images.githubusercontent.com/740128/64252095-f97d0c80-cee7-11e9-845e-5dfae37a9129.png)

gif attached of trying to add a label with `@`, adding one manually in the UI, and trying to remove a label with `y`.

Tested on Windows 10, Brave 0.68 (Chrome 76)

![2019-09-04_07-47-00](https://user-images.githubusercontent.com/740128/64252407-dd2d9f80-cee8-11e9-9417-8fb2df02b3e0.gif)

**Comment by GaryFurash** [comment]
Found this issue also.

**Comment by mgsloan** [comment]
@ErikOsterud Glad you appreciate it, and thanks for reporting this issue!  I've uploaded version 61 with a fix for this
