### ISSUE TITLE
Scheduling shortcuts broken with Todoist Version 968

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#85]
Typing **t** followed by any of the single-character shortcuts (**c**, **r**, **s**, **t**, **w**) no longer works.

**Comment by jon-amused** [comment]
Also having this issue

**Comment by nakaomote** [comment]
+1

**Comment by jamesx4** [comment]
+1

**Comment by mgsloan** [comment]
Yep I'm seeing this too, will hopefully have time to fix it this evening

**Comment by mgsloan** [comment]
Thanks for reporting!  I've uploaded version 61 with a fix

**Comment by jon-amused** [comment]
> Thanks for reporting! I've uploaded version 61 with a fix

Thanks for fixing so fast!!  I've really come to depend on the shortcuts in Todoist!
