### ISSUE TITLE
Documentation error: Wrong shortcut for indent/dedent in Google Sheet

### ISSUE THREAD

**Issue by frankydee** [mgsloan/todoist-shortcuts#86]
I was perusing the shortcuts in the Google Sheet accessible from Todoist via <kbd>?</kbd> and noticed a mistake. 

In the "Manipulate" section, the shortut for "dedent task at cursor" is **shift+l | shift+left** whilst "indent task at cursor" is **shift+h | shift+right**.     The **shift+l** and **shift+h** should be swapped. 

Thanks

**Comment by mgsloan** [comment]
Ah, good catch, thanks!  I've updated the sheet
