### ISSUE TITLE
Several keyboard shortcuts stopped working with Version 972

### ISSUE THREAD

**Issue by h-chatha** [mgsloan/todoist-shortcuts#87]
Shortcuts like v, o, e, #, ? with the latest release Version 972.

**Comment by ismig** [comment]
I use Todoist Beta and these shortcuts have been busted for several days there. Some of them work on _selected_ tasks, but eh..

**Comment by mgsloan** [comment]
Thanks for reporting!  Fix included in version 63

**Comment by h-chatha** [comment]
Perfect. Thank you.
