### ISSUE TITLE
New shortcut request for new Task View

### ISSUE THREAD

**Issue by h-chatha** [mgsloan/todoist-shortcuts#88]
It will be great to add a shortcut for new Task View. Perhaps "i"?

**Comment by frankydee** [comment]
+1 from me.

And I suppose (if I may be so bold) once in the Task View, we could do with a few new shortcuts to navigate in there  :blush: :

- Navigate to parent task (<kbd>shift</kbd> + <kbd>p</kbd> maybe?)
- Select Subtasks tab (<kbd>shift</kbd> + <kbd>s</kbd> maybe?)
- Select Comments tab (<kbd>shift</kbd> + <kbd>c</kbd>, or <kbd>c</kbd> maybe?)
- Select Activity tab (<kbd>shift</kbd> + <kbd>a</kbd> maybe?)

The reason for using the <kbd>shift</kbd> modifier key it so keep it conflict free with the other existing shortcuts (i.e. <kbd>p</kbd>  and <kbd>s</kbd> are already assigned to sorting by priority and date, whilst <kbd>a</kbd> is assigned to "add new task at the bottom of the list").

This way, it's consistent accross the task view and easy to remember (i.e. "to navigate within the Task View, use the <kbd>shift</kbd> key and the first letter of whatever you want to do").   Also, if Todoist were ever to implement sorting of sub tasks within that view (which I suspect they eventually will??), then <kbd>p</kbd> and <kbd>s</kbd> could be used for sorting, just like they are elsewhere.   You could also assign <kbd>a</kbd> to "add new sub task at the bottom of the list" if you wished.

Consistency, consistency, consistency  :wink:

P.S.: @mgsloan, maybe it's bad practice/confusing to just cram lots of requests in the comment of another request?? :dizzy_face:...  But I thought it still fitted with the name of the Issue.   I can raise a seperate request if you prefer. Please advise 😊

**Comment by mgsloan** [comment]
I've implemented an initial swing at this, and released it in version 65!  It's certainly not perfect, but better than nothing.

Thanks for the input @frankydee I agree consistency is important, but have prioritized consistency with the meaning of the existing keybindings.  `shift+a` is unfortunately already taken.  It's fine to add other requests to an existing issue.

**Comment by h-chatha** [comment]
@mgsloan thank you!

**Comment by frankydee** [comment]
Thank you @mgsloan!   (you're right I had forgotten about the built-in `shift+a`  shortcut!)

I especially like the `h` to navigate to the parent task, very handy (I've chosen to memorise it as `h` for hierarchy 😉 ).  

Thanks again, great work and quick turnaround as always! 👍 😄

**Comment by AndyHickman** [comment]
Michael, you a such a champ! Thank you!

**Comment by mgsloan** [comment]
Glad y'all appreciate my work on this!

`h` for hierarchy is a good mnemonic.  The basis of my choice was that `h` generally means "move to the left" for vim style keyboard shortcuts.  In the normal view when the cursor is on a nested task pressing `h` will focus the parent and collapse the nesting.

**Comment by AndyHickman** [comment]
Hey Michael,
I'm noticing that "y" to change labels does not work outside of task view
ever since you added the "i" for task view. It DOES work within task view,
but not outside of it.
-Andy

**Comment by mgsloan** [comment]
Hmm, that's curious!  For me "y" works on both todoist.com and
beta.todoist.com.  Does reloading the tab work?

**Comment by AndyHickman** [comment]
I tried reloading and it did not work. I also turning the extension off,
reloading, turning the extension back on, and reloading and that did not
work either.
This is the type of browser I am using: https://whatsmybrowser.org/b/Y5F4L3D

I am using v975 of the web version of Todoist.

**Comment by mgsloan** [comment]
@AndyHickman Oops, looks like version 66 didn't upload properly for chrome yesterday when I was fixing #95 . After updating extensions is it fixed now?

My Todoist version is 9107.  It may be hard to fix bugs if some users are on pre-foundation todoist, hmmm

**Comment by AndyHickman** [comment]
Yes, that did the trick! 👍

Is your version number so high because you are using beta?

Also, when you say, "It may be hard to fix bugs if some users are on
pre-foundation todoist" are you implying that v975 is pre-foundation -
because if you are, I want to clarify that non-beta foundations started in
v972, so I would think that users of your extension, who are most likely on
the "power user" spectrum and therefore also eager to update Todoist to the
latest version, are all running a version of foundations at this point. If
that is not what you meant, feel free to ignore this comment and do not
feel obliged to further explain.

Thank you for your quality work - this extension is so useful!

**Comment by mgsloan** [comment]
I edited my comment a little after making it.  When I initially wrote it I
made the incorrect assumption that the new release had changed the version
number scheme, but instead it was just the beta version numbering scheme.

I'm so glad you appreciate the extension so much!
