### ISSUE TITLE
new shortcut for assigning a task

### ISSUE THREAD

**Issue by mrderiuzz** [mgsloan/todoist-shortcuts#89]
currently we are lacking a shortcut to assign a task to someone. I suggest for it to be a plus sign "+" as it is also _+name_ for natural language input

thanks in advance!

**Comment by mgsloan** [comment]
Hmm, I haven't tried team Todoist.  I just use my personal account, and so don't see the UI for this.  Perhaps try opening a PR adding it?

Thanks!

**Comment by mrderiuzz** [comment]
I'm afraid I wouldn't exactly know how. But you can easily enable that, just go to one of your projects, click share options and type in any email (doesn't even have to exist). This will enable you the option to assign tasks. let me know if you can see it now?

**Comment by mgsloan** [comment]
Ah, thanks for the info, that worked.  I've added this in version 67!
