### ISSUE TITLE
[beta] Scheduling keys broken in "Today" & "Next 7 days"

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#92]
Note, this issue only happens in beta.todoist.com (for now).

The broken keys are **t** and **T**. Instead of opening the scheduling window, they take me into task-editing mode.
Weirdly, this only happens in the "Today" and "Next 7 days" views. (Er...not true, it also happens in certain kinds of custom filter views, but trying to describe that would just muddle things.)

**Comment by mgsloan** [comment]
Thanks for reporting this issue!  It's now fixed in version 64.
