### ISSUE TITLE
Feature request: shortcuts for manipulating sections

### ISSUE THREAD

**Issue by ismig** [mgsloan/todoist-shortcuts#93]
[Sections](https://get.todoist.help/hc/en-us/articles/360003788739-Sections) are a major new feature Todoist Foundations. It'd be great to have a few shortcuts for working with them:

- create a new section
- set the cursor on a section (via the **j**/**k** keys and the mouse)
- edit the section at cursor (hit _enter_)
- create tasks in a section (**o**/**O**)
- collapse/expand the section at the cursor (**h**/**l**)
- delete a section (**#**)

**Comment by mgsloan** [comment]
Being able to expand a section means the cursor will need to visit things
which are not tasks, so not a trivial change.

It'd also be nice to have a way to move tasks in and out of sections.

I'm not really seeing what advantages these have over nested projects, IMHO
the feature seems a bit redundant with those.  I'll consider adding
shortcuts for them, but I don't use them yet, and not sure why I would.
Perhaps if there's sufficient user demand

**Comment by mgsloan** [comment]
Above comment was written by email so I didn't see your edits clarifying more shortcuts than just (h/l).  Your suggestions seem quite reasonable!

**Comment by sazwqa** [comment]
Also, the keyboard shortcut "s" has been reserved by Todoist for "Creating a section" and hence "suggested date or smart scheduler" shortcut ("t s") instead invokes the "create a section" function.

**Comment by mgsloan** [comment]
Thanks for the info about Todoist's shortcut choices.

There is no conflict between `t s` and the create a section shortcut.  There is, however a conflict between using `s` for "sorting by date".  Will have to consider whether to change that or not.  I'd be surprised if anyone uses that a ton.

> More -- "d" is keyword that Todoist has dedicated for "sorting by date"

There's no way I'm going to make todoist-shortcuts consistent with that one, I have way too much muscle memory for d for "done", and I imagine users do too.

**Comment by mgsloan** [comment]
@basilhalperin Good catch, I've fixed the behavior of `a` in the presence of sections in version 146

**Comment by mgsloan** [comment]
Closing this as wontfix.  My reasoning is:

1. Section manipulation seems like it should be a rare thing, as it's just when rejiggering your systems, or planning a new project.  So can use the mouse in these cases.  Similar reasoning to this is why there are no bindings for adding / rearranging projects.
2. I don't use sections
