### ISSUE TITLE
Shortcut "i" stopped working with new version of Todoist

### ISSUE THREAD

**Issue by h-chatha** [mgsloan/todoist-shortcuts#96]
@mgsloan it looks like the shortcut `i`  has stopped working with the new version of Todoist. Could you please take a look? Thanks.

**Comment by mgsloan** [comment]
Oops, looks like version 66 didn't upload properly for chrome yesterday when I was fixing https://github.com/mgsloan/todoist-shortcuts/issues/95 .  After updating extensions is it fixed now?

**Comment by h-chatha** [comment]
It turns out that the reason `i` stopped working for me was due to [Toggl Button: Productivity & Time Tracker](https://chrome.google.com/webstore/detail/toggl-button-productivity/oejgccbfbmkkpaidnkphaiaecficdnfn). If I remove the Toggl extension, `i` shortcut starts working.

**Comment by mgsloan** [comment]
Ah, thanks for diagnosing the problem!  Looks like the toggl extension is reusing the `task_view` class for its button, causing this issue.  I've included a fix in version 67

**Comment by h-chatha** [comment]
Thank you very much.
