### ISSUE TITLE
New shortcut request for jumping to a project from any task in search results

### ISSUE THREAD

**Issue by h-chatha** [mgsloan/todoist-shortcuts#97]
When you perform a search in Todoist, it returns the matching tasks in the search results. The name of the project (to which the task belongs to) is displayed on the far right of the task. Before the new "Foundations" implementation, you could click on the project name in the task to quickly jump to the project. Now, when you hover over the project name, the project name is replaced by the new "Task View", Calendar and Comments icons. You have to click on the "..." to open the context menu and then click on "Go to project" to jump to the project. Please see attached image as a reference.

It would be great to have a keyboard shortcut to quickly jump to the task's project. Perhaps `shift + p`? For those of us who spend inordinate amount of time searching tasks then organically browsing tasks, this would be life saver.

Thank you @mgsloan 
![Go_To_Project](https://user-images.githubusercontent.com/52041941/68547849-9b234d00-03b4-11ea-9cbb-3819dadd7628.png)

**Comment by mgsloan** [comment]
I believe this binding already exists!  `shift+g`!

**Comment by h-chatha** [comment]
@mgsloan that worked. Thank you.
