### ISSUE TITLE
"Move to Project" shortcut (v) no longer works for projects with sections

### ISSUE THREAD

**Issue by GraphicThinkPad** [mgsloan/todoist-shortcuts#98]
When attempting to move a task to a project that has sections within it using the `v` shortcut, the move fails completely.

In the past, moving a task to a section-filled project with v would open a secondary menu where the project's sections were made available to choose from. Now, nothing happens when `v` is used to move a task to a project with sections--the task is not moved anywhere.

**Comment by mgsloan** [comment]
Hi, this is a bug with Todoist not with todoist-shortcuts.  It also doesn't work when I use the mouse or disable the extension.  I have reported this bug via the form here: https://get.todoist.help/hc/en-us/requests/new

**Comment by mgsloan** [comment]
Leaving the issue open for now to remind me to try this out once it's resolved upstream.

**Comment by mgsloan** [comment]
Looks like this is fixed on beta.todoist.com
